### ISSUE TITLE
Incorrect relation of units Tesla and Weber

### ISSUE THREAD

**Issue by HoWilgh** [qudt/qudt-public-repo#1003]
The relation between the unit Tesla on https://qudt.org/vocab/unit/T and the Weber unit is incorrect.

The unit of the MagneticFluxDensity is defined as 
Tesla=kg⋅s^−2⋅A^−1=kg/(s^2.A)=Weber/m^2
or expressed with ISQ quantities (with exponents)
"T-2 L0 M+1 I-1 Θ0 N0 J0"

The related unit of MagneticFlux is defined as 
N.m/A= kg.m/(s^2).m/A= kg.m^2/(s^2.A)=Weber
or expressed with ISQ quantities 
"T-2 L+2 M+1 I-1 Θ0 N0 J0"

So, on the above site T=Weber/m=Wb/m, which is wrong and should be T=Wb/m^2.

See also:
https://ieeemagnetics.org/files/ieeemagnetics/2022-04/magnetic_units.pdf
https://ec.europa.eu/health/scientific_committees/opinions_layman/en/electromagnetic-fields/glossary/tuv/tesla.htm
https://en.wikipedia.org/wiki/Tesla_(unit)

**Comment by steveraysteveray** [comment]
Thanks for the great catch. Luckily, I see it is just in the description that there is an error, and not in the RDF relations.
