### ISSUE TITLE
wrong offset in prefixed units like MilliDEG_C etc

### ISSUE THREAD

**Issue by Rdataflow** [qudt/qudt-public-repo#1045]
**Situation**
According to the Wiki unit conversion uses this formula
$$z(y) = \frac{{(y + CO_{y})}  \cdot CM_y}{CM_z} - CO_{z}$$
which implies offset to be in the *native* scale (i.e. Fahrenheit has offset 459.67 based on Fahrenheit units)
source https://github.com/qudt/qudt-public-repo/wiki/Support-for-measures-of-absolute-values-and-for-intervals-(differences)#converting-units-on-linear-scales
see also https://github.com/qudt/qudt-public-repo/issues/413#issuecomment-856819467

**Issue**
units like MilliDEG_C have inconsistent offsets (using other than the *native* scale)

**Expected**
MilliDEG_C should have offset of 273150 (based on native MilliDEG_C units)

**Actual**
MilliDEG_C has offset of 273.15

**Impact**
The proposed formula returns unexpectedly wrong results for such cases. Therefore those offsets may be corrected to consistently use the *native scale units*

cc @steveraysteveray

**Comment by steveraysteveray** [comment]
Great catch! Given enough eyeballs, all bugs are indeed shallow! I'll make the fix. At this point, I believe MilliDEG_C is the only such unit in the current vocabulary.

**Comment by Rdataflow** [comment]
🎉
