### ISSUE TITLE
Make the ontology (schema) URIs dereferenceable

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#107]
The URIs for all the resources (classes, properties) used in QUDT should dereference - e.g. 
http://qudt.org/schema/qudt/QuantityKind
http://qudt.org/schema/qudt/DerivedUnit
http://qudt.org/schema/qudt/iec61360Code

**Comment by steveraysteveray** [comment]
Agreed. It's on my list...

**Comment by dr-shorthair** [comment]
I had checked to see if an existing issue already mentioned it but couldn't see anything. 
Perhaps you could convert your 'list' into GitHub issues, so that there is some transparency/roadmap for users? 

QUDT was 'stuck' for so long that some potential users moved elsewhere (e.g. to https://github.com/HajoRijgersberg/OM see https://github.com/HajoRijgersberg/OM/issues/22 ). Now QUDT is making progress again, it might be worth advertising the areas where work is planned.
