### ISSUE TITLE
M3 description incorrect

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#108]
http://qudt.org/vocab/unit/M3

"The SI unit of volume, equal to **106 cm3**, 1000 liters, 35.3147 ft3, or **1.307 95 yd3**. "

The items in **bold** are incorrect.

**Comment by steveraysteveray** [comment]
Thanks Simon. Hadn't examined the description. I agree with the cm3 erratum, but not the yd3. Here's the output from my handy conversion SPARQL query:

To convert	Cubic Meter	into	Cubic Mile	multiply by	2.39912758316496E-10
To convert	Cubic Meter	into	MegaL	multiply by	1.0E-6
To convert	Cubic Meter	into	Acre Foot	multiply by	8.107131937899124E-4
To convert	Cubic Meter	into	DecaM3	multiply by	0.001e0
To convert	Cubic Meter	into	Standard	multiply by	0.21404109589041098e0
To convert	Cubic Meter	into	Cord	multiply by	0.27624309392265195e0
To convert	Cubic Meter	into	Register Ton	multiply by	0.3531466672148859e0
To convert	Cubic Meter	into	TON_SHIPPING_US	multiply by	0.8829242450997704e0
To convert	Cubic Meter	into	KiloL	multiply by	1.0e0
To convert	Cubic Meter	into	Stere	multiply by	1.0e0
To convert	Cubic Meter	into	Cubic Yard	multiply by	1.3079506193143922e0
To convert	Cubic Meter	into	BBL_UK_PET	multiply by	6.284833690730875e0
To convert	Cubic Meter	into	BBL_US	multiply by	6.28981056977507e0
To convert	Cubic Meter	into	BBL_US_DRY	multiply by	8.6484093756776e0
To convert	Cubic Meter	into	HectoL	multiply by	10.0e0
To convert	Cubic Meter	into	bushel (UK)	multiply by	27.496156037385973e0
To convert	Cubic Meter	into	bushel (US)	multiply by	28.377593392788178e0
To convert	Cubic Meter	into	Cubic Foot	multiply by	35.31466672148859e0
To convert	Cubic Meter	into	DecaL	multiply by	100.0e0
To convert	Cubic Meter	into	PK_UK	multiply by	109.98461205292769e0
To convert	Cubic Meter	into	GAL_UK	multiply by	219.96924829908778e0
To convert	Cubic Meter	into	Imperial Gallon	multiply by	219.96924829908778e0
To convert	Cubic Meter	into	Dry Gallon US	multiply by	227.02074611153702e0
To convert	Cubic Meter	into	US Gallon	multiply by	264.1720372841846e0
To convert	Cubic Meter	into	Board Foot	multiply by	423.728813559322e0
To convert	Cubic Meter	into	QT_UK	multiply by	879.8769931963511e0
To convert	Cubic Meter	into	Quart	multiply by	879.8789286594165e0
To convert	Cubic Meter	into	US Dry Quart	multiply by	908.0829842688559e0
To convert	Cubic Meter	into	DeciM3	multiply by	1000.0e0
To convert	Cubic Meter	into	Liter	multiply by	1000.0e0
To convert	Cubic Meter	into	US Liquid Quart	multiply by	1056.6881491367385e0
To convert	Cubic Meter	into	PINT_UK	multiply by	1759.7538315560112e0
To convert	Cubic Meter	into	Imperial Pint	multiply by	1759.7539863927022e0
To convert	Cubic Meter	into	Pint US Dry	multiply by	1816.165969716911e0
To convert	Cubic Meter	into	US Dry Pint	multiply by	1816.165969716911e0
To convert	Cubic Meter	into	US Liquid Pint	multiply by	2113.376298273477e0
To convert	Cubic Meter	into	US Liquid Cup	multiply by	4226.752596546954e0
To convert	Cubic Meter	into	CUP_US	multiply by	4226.753489819019e0
To convert	Cubic Meter	into	GI_UK	multiply by	7039.016564917682e0
To convert	Cubic Meter	into	GI_US	multiply by	8453.505193093908e0
To convert	Cubic Meter	into	DeciL	multiply by	10000.0e0
To convert	Cubic Meter	into	US Liquid Ounce	multiply by	33814.02265896594e0
To convert	Cubic Meter	into	OZ_VOL_UK (liquid volume)	multiply by	35195.07972785404e0
To convert	Cubic Meter	into	Cubic Inch	multiply by	61023.74409473229e0
To convert	Cubic Meter	into	Tablespoon	multiply by	67628.04165909007e0
To convert	Cubic Meter	into	CentiL	multiply by	99999.99999999999e0
To convert	Cubic Meter	into	Teaspoon	multiply by	202884.12484006365e0
To convert	Cubic Meter	into	MilliL	multiply by	1000000.0e0
To convert	Cubic Meter	into	cubic centimeter	multiply by	1000000.0e0
To convert	Cubic Meter	into	Cubic Millimeter	multiply by	9.999999999999999E8
To convert	Cubic Meter	into	MicroL	multiply by	9.999999999999999E8
To convert	Cubic Meter	into	Planck Volume	multiply by	2.3673177579606978E104

Will fix the description.

**Comment by dr-shorthair** [comment]
Its the space in the decimal string that is a bit confusing

**Comment by dr-shorthair** [comment]
And I don't understand why you have closed the issue _prior_ to implementing the fix ...

**Comment by steveraysteveray** [comment]
Fair point. The PR has been submitted, but I could have waited...
