### ISSUE TITLE
Where to put fundamental constants? They are in 2 places right now.

### ISSUE THREAD

**Issue by steveraysteveray** [qudt/qudt-public-repo#12]
The two files:
/vocab/quantitykinds/standards-based-quantitykinds/VOCAB_QUDT-QUANTITY-KINDS-NIST-CONSTANTS-v2.0.ttl
and
/vocab/constants/VOCAB_qudt-constants-nist-v1.2.ttl

both contain almost identical content (and lots of it). One of them has to go. The second file is the only one in the "constants" folder. There are several design issues:

The constants are all instances of either qudt:PhysicalConstant (defining the constant) or qudt:ConstantValue (giving the numerical value). Should either or both of these really have the namespace of "quantitykind"? Maybe "constant" would be a better namespace, since they really are different animals than quantity kinds (IMO).

If we do switch the namespace to "constant", then maybe the constants folder is a good home.

This design decision might also affect the "Characteristic Numbers" found in several of the quantity kind folders, which also are in the quantitykind namespace.

Furthermore, there are 5 constants that are defined in the "unit" namespace in the above files (which is how I bumped into this issue):
unit:BohrRadius
unit:EV (also defined in atomic and nuclear physics)
unit:ElementaryCharge (also defined in electromagnetism)
unit:HartreeEnergy
unit:PlanckConstant (also defined in atomic and nuclear physics, although seems like it shouldn't be)

We should put them into whatever namespace we decide on for the constants, and remove the ones that are really units.

Comments? Opinions?

**Comment by jhodgesatmb** [comment]
We started talking about this other times. I just want to be consistent. Why were things made units or quantities when they weren’t, really, in the first place? If we change what they are, now, might we cross some line that was actually accommodated with the earlier approach?

Jack Hodges, Ph.D.
Arbor Studios

**Comment by steveraysteveray** [comment]
PR #27 addresses this issue by comparing the two files, and moving the consolidated file into the vocab/constants folder. The is one constant remaining (constant:Value_AtomicUnitOf2ndHyperpolarizability) that has a link to an undefined unit, 
unit:QuarticCoulombMeterPerCubicEnergy.
At some point we need somebody to double check it, and also tie in the appropriate quantity kind and dimension vector.
I believe the correct dimension vector is qkdv:A0E4L-5I0M-3H0T10D0, but this is only 
inferred from the name of the unit.
