### ISSUE TITLE
qudt.type prefix

### ISSUE THREAD

**Issue by ktk** [qudt/qudt-public-repo#135]
I'm checking out the 2.1 release for integration in our vocab browsing tool. This prefix here looks strange to me:

https://github.com/qudt/qudt-public-repo/blob/78888c26c8ec9c3bd3d935e037665b89f3e7fe74/schema/SCHEMA_QUDT-DATATYPE-v2.1.ttl#L16

I guess it's probably valid RDF but I would say it's very uncommon. What is the idea of using a dot in here?

**Comment by jhodgesatmb** [comment]
I am personally big on developing industry-wide best practices for ontologies and semantic technologies. It may indeed be odd to put a period in a prefix but I haven’t written or seen a best practices document saying how to name cascaded prefixes. Have you? Would you expect any of these:

  - qudt_type
  - qudt-type
  - qudttype

Or would you expect something else?

Jack

**Comment by ktk** [comment]
I have not seen anything like that either. I personally use prefixes with `-` as well but noticed that some syntax highlighter for Turtle already choke on that.

I'm not a big fan of `_` for anything, does not look pretty IMO and I think Turtle should look pretty.
