### ISSUE TITLE
PINT-compatible export

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#163]
PINT is a Python library for manipulation of quantities and units. 
It appears to be very actively maintained and well supported. 
The documentation is here: https://pint.readthedocs.io/en/stable/ 

To get a sense of the scope of PINT here is the default dataset: 
https://github.com/hgrecco/pint/blob/master/pint/default_en.txt

I haven't dug too much deeper, but thought it was worth drawing attention to this as a potentially significant implementation route in a very popular scientific programming environment.

**Comment by steveraysteveray** [comment]
Very interesting indeed. Thanks.
