### ISSUE TITLE
unit:CentiM is missing a qudt:Unit type statement

### ISSUE THREAD

**Issue by Toni100** [qudt/qudt-public-repo#166]
In the Turtle file http://qudt.org/2.1/vocab/unit the unit `unit:CentiM` is missing a `a qudt:Unit` statement.
While this could potentially be inferred from the other type statements, it deviates from the practice of adding an explicit `a qudt:Unit` to every unit: CentiM is therefore an outlier.

**Comment by steveraysteveray** [comment]
Thanks for this catch. Something odd happened where a handful of units lost their declaration as direct instances of qudt:Unit. This is fixed in PR #167 (and eventually will migrate from the GitHub file to the resolvable file you referenced. I only refresh those every few weeks...)
