### ISSUE TITLE
VOCAB_unicode-v1.2.ttl is Self Importing

### ISSUE THREAD

**Issue by dm-work** [qudt/qudt-public-repo#182]
The file:  `vocab/codes/VOCAB_unicode-v1.2.ttl` declares an owl:versionIRI for itself, then imports the same IRI as seen in the fragment:

```
<http://qudt.org/2.0/vocab/unicode>
  rdf:type owl:Ontology ;
  owl:imports <http://qudt.org/2.0/schema/unicode> ;
  owl:versionIRI <http://qudt.org/2.0/schema/unicode> ;

```

**Comment by steveraysteveray** [comment]
Thanks.
The QUDT Board will have to discuss whether all these Unicodes even belong in the QUDT ontology set.

- Steve
