### ISSUE TITLE
VOCAB_QUDT-QUANTITY-KINDS-ISQ-INFORMATION-SCIENCE-AND-TECHNOLOGY-v2.0.ttl Contains Missing Imports

### ISSUE THREAD

**Issue by dm-work** [qudt/qudt-public-repo#187]
The file, `VOCAB_QUDT-QUANTITY-KINDS-ISQ-INFORMATION-SCIENCE-AND-TECHNOLOGY-v2.0.ttl`, contains imports of resources that are not included in the [QUDT Release 2.1.4](https://github.com/qudt/qudt-public-repo/releases/tag/v2.1.4):

```
<http://qudt.org/2.0/vocab/isq/quantitykind/information-science-and-technology>
  owl:imports <http://qudt.org/2.0/vocab/dimensionvector> ;
  owl:imports <http://qudt.org/2.0/vocab/quantitykind/information-theory> ;
  owl:imports <http://qudt.org/2.0/vocab/quantitykind/si> ;
  owl:imports <http://qudt.org/2.0/vocab/unit/informatics> ;
  owl:versionIRI <http://qudt.org/2.0/vocab/quantitykinds/si> ;
```

The import of `http://qudt.org/2.0/vocab/quantitykinds/si` appears to be a self-import following the declaration of the same IRI as the resources `owl:versionIRI`.

**Comment by steveraysteveray** [comment]
See my comment on Issue #188.
