### ISSUE TITLE
confusion between stokes and stere

### ISSUE THREAD

**Issue by Toni100** [qudt/qudt-public-repo#199]
On http://www.qudt.org/doc/2020/08/DOC_VOCAB-UNITS-ALL-v2.1.html there is the entry `unit:ST` Stokes. Clicking on "html" next to is leads to http://qudt.org/vocab/unit/ST.html which talks about the unit stere.

Then there is http://qudt.org/vocab/unit/St.html (note the lower-case "t") which displays in the box ` unit:ST ` (note the upper-case "T") and talks about stokes.

**Comment by Toni100** [comment]
In general, I think it might be dangerous to have URIs which differ only in the letter-case.

**Comment by jhodgesatmb** [comment]
You are right of course but these are known notations and we adhering to a naming convention that is human readable. There are only a few clashes like this and the bug you reported is the result of a migration algorithm and not a problem with qnames in general, which are always case sensitive.

Jack Hodges, Ph.D.
Arbor Studios

**Comment by steveraysteveray** [comment]
Actually, we fixed this a while ago, with the Stere being unit:STR and the Stokes being unit:ST, but during a GitHub merge episode some of it reverted. I'll take another look.

**Comment by steveraysteveray** [comment]
Please check the pages/popups/links now. I think it is all correct. 
I believe that the problem might have been that the old St.html file somehow wasn't being properly overwritten during the publishing script run. Hard to say. I'll keep an eye on this unit next time I publish.

**Comment by Toni100** [comment]
http://www.qudt.org/doc/2020/08/DOC_VOCAB-UNITS-ALL-v2.1.html now looks good.
http://qudt.org/vocab/unit/ST.html still talks about stere.

**Comment by steveraysteveray** [comment]
Did you try refreshing your browser?

 
- Steve

**Comment by Toni100** [comment]
Refreshing did fix it, thanks. All seems good now.
