### ISSUE TITLE
PSI appears to be missing

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#207]
Several derived units but not the base unit for PSI

**Comment by steveraysteveray** [comment]
Great catch. Terrible oversight! Is added in the next PR.

**Comment by steveraysteveray** [comment]
Actually, I see LB-PER-IN2, so the real question is whether I should just rename that one, or have two units that are owl:sameAs, or some other solution...
I definitely agree that PSI is the normal usage.

**Comment by steveraysteveray** [comment]
Actually, let me amend my comment again. LB-PER-IN2 is for the unit of pound of mass, not the pound of force (which would have had the qname of LB_F-PER-IN2 anyway). So I will add PSI as a new unit.

**Comment by steveraysteveray** [comment]
Wow, I need more coffee. I now see we already have LB_F-PER-IN2. I'm going to do an owl:sameAs for the two.

**Comment by dr-shorthair** [comment]
A number of derived units including the symbol 'PSI' are already in the catalog. But not the 'base' PSI!
