### ISSUE TITLE
Wrong entailments due to qudt:exactMatch

### ISSUE THREAD

**Issue by jmkeil** [qudt/qudt-public-repo#219]
The ontology modules http://qudt.org/2.1/schema/qudt, http://qudt.org/2.1/vocab/constant, and http://qudt.org/2.1/vocab/quantitykind entail 
```
constant:MagneticConstant                 rdf:type qudt:Unit .
quantitykind:AngularMomentum              rdf:type qudt:Unit .
quantitykind:AuxillaryMagneticField       rdf:type qudt:Unit .
quantitykind:CoefficientOfHeatTransfer    rdf:type qudt:Unit .
quantitykind:Density                      rdf:type qudt:Unit .
quantitykind:ElectricDisplacement         rdf:type qudt:Unit .
quantitykind:ElectricFluxDensity          rdf:type qudt:Unit .
quantitykind:ElectricPotential            rdf:type qudt:Unit .
quantitykind:ElectromagneticEnergyDensity rdf:type qudt:Unit .
quantitykind:EnergyPerElectricCharge      rdf:type qudt:Unit .
quantitykind:InternalEnergy               rdf:type qudt:Unit .
quantitykind:IsothermalCompressibility    rdf:type qudt:Unit .
quantitykind:MagneticAreaMoment           rdf:type qudt:Unit .
quantitykind:MagneticFieldStrength        rdf:type qudt:Unit .
quantitykind:MomentOfForce                rdf:type qudt:Unit .
quantitykind:VolumicElectromagneticEnergy rdf:type qudt:Unit .
```
due to 
```
qudt:exactMatch rdfs:range qudt:Unit .
```
I recommend to replace `qudt:exactMatch` with `owl:sameAs` or `skos:exactMatch` (depending on the particular case), instead of fixing `qudt:exactMatch`.

**Comment by dr-shorthair** [comment]
The global range constraints on `qudt:exactMatch` appears to reach too far. Maybe `qudt:Concept` instead. 

However, note that the SKOS mapping relations "are used to state mapping (alignment) links between SKOS concepts in different concept schemes". see https://www.w3.org/TR/skos-reference/#mapping So if `qudt:exactMatch` is intended to be similar to `skos:exactMatch`, then it should not be used to assert relationships within the QUDT vocabularies, only to assert relationships to items in other vocabs.

**Comment by jmkeil** [comment]
> However, note that the SKOS mapping relations "are used to state mapping (alignment) links between SKOS concepts in different concept schemes". see https://www.w3.org/TR/skos-reference/#mapping So if `qudt:exactMatch` is intended to be similar to `skos:exactMatch`, then it should not be used to assert relationships within the QUDT vocabularies, only to assert relationships to items in other vocabs.

Good point. Was not aware of that aspect. Thanks.

**Comment by ektrah** [comment]
Still an issue in v2.1.26. All of these quantity kinds are inferred to be a unit:

* quantitykind:Acceleration
* quantitykind:Angle
* quantitykind:AngularImpulse
* quantitykind:AngularMomentum
* quantitykind:Density
* quantitykind:ElectricDisplacement
* quantitykind:ElectricFluxDensity
* quantitykind:ElectricPotential
* quantitykind:ElectricPotentialDifference
* quantitykind:ElectromagneticEnergyDensity
* quantitykind:ElectromagneticPermeability
* quantitykind:EnergyInternal
* quantitykind:EnergyPerElectricCharge
* quantitykind:InternalEnergy
* quantitykind:InversePressure
* quantitykind:IonDensity
* quantitykind:IsothermalCompressibility
* quantitykind:LinearAcceleration
* quantitykind:LinearMomentum
* quantitykind:LinearStrain
* quantitykind:LinearVelocity
* quantitykind:MagneticAreaMoment
* quantitykind:MagneticMoment
* quantitykind:MassDensity
* quantitykind:MolarAbsorptionCoefficient
* quantitykind:MolarAttenuationCoefficient
* quantitykind:MomentOfForce
* quantitykind:MomentOfInertia
* quantitykind:Momentum
* quantitykind:Permeability
* quantitykind:PlaneAngle
* quantitykind:Strain
* quantitykind:ThermodynamicEnergy
* quantitykind:Torque
* quantitykind:Velocity
* quantitykind:Voltage
* quantitykind:VolumeFlowRate
* quantitykind:VolumePerUnitTime
* quantitykind:VolumicElectromagneticEnergy

**Comment by steveraysteveray** [comment]
After finally taking a look at this, I'm not sure why qudt:exactMatch had an rdfs:range value of qudt:Unit. I'll remove that.

Of course, this only affects the OWL schema. The SHACL schema is fine.
