### ISSUE TITLE
Allowing appropriate citation of QUDT through DOI

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [qudt/qudt-public-repo#227]
Dear QUDT-Team,

Having a DOI, e.g. though Zenodo.org service, for a github repository makes the work and code easily citable in scientific publications. I was wondering if your are planning to include this for https://github.com/qudt/qudt-public-repo ?

Here is a guide: https://genr.eu/wp/cite/

Best

Georg

**Comment by steveraysteveray** [comment]
Hi Georg,
We have registered through FAIRsharing. See https://doi.org/10.25504/FAIRsharing.d3pqw7

Now I'm wondering what is the best practice for DOI registration. Just one, or many?
In any case, I should add the above DOI link to our documentation.

Thanks,

- Steve

**Comment by steveraysteveray** [comment]
I do like the way Zenodo links to each GitHub Release...

**Comment by GeorgFerdinandSchneider** [comment]
Good so there exists a DOI aleady. I made a quick check in the README.md and could not find a link/ section mentioning it -> Potentially and enhancement is to add something like

# Citation

If you like to reference QUDT ontologies in scientific literature you may refer to DOI: https://doi.org/10.25504/FAIRsharing.d3pqw7

or similar

In general I would be in favor of a single DOI - you might evaluate the services in on your team to decide which one to take

Best

Georg

**Comment by steveraysteveray** [comment]
Thanks! We'll take action to fix this.

**Comment by steveraysteveray** [comment]
The FAIRsharing DOI is now on the GitHub README file, and will soon be on our homepage at qudt.org.

**Comment by GeorgFerdinandSchneider** [comment]
excellent!
