### ISSUE TITLE
Duplicate units

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#237]
unit:BTU_IT-FT-PER-FT2-HR-DEG_F == unit:BTU_IT-FT-PER-HR-FT2-DEG_F
unit:BTU_TH-IN-PER-FT2-HR-DEG_F == unit:BTU_TH-IN-PER-HR-FT2-DEG_F

**Comment by jhodgesatmb** [comment]
If I hadn’t created some of those it would be funny. This is perhaps the result of automation.

**Comment by steveraysteveray** [comment]
Yes, agreed. We only recently added the qname rule that in the absence of any other rule, go alphabetically. (See Rule 2.5 [here](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines#qname-naming-rules)).

So, FT2-HR beats HR-FT2.

**Comment by steveraysteveray** [comment]
Resolved in PR #242
