### ISSUE TITLE
Label issues

### ISSUE THREAD

**Issue by SirkoS** [qudt/qudt-public-repo#26]
While rerunning [some old analysis scripts](https://github.com/fusion-jena/unit-ontology-review) of ours for the [mapping between SWEET and QUDT2](https://github.com/ESIPFed/sweet/issues/60), I found some issues regarding the labels and IRIs within QUDT2:

http://qudt.org/vocab/unit/KiloBIT-PER-SEC
http://qudt.org/vocab/unit/KilobitsPerSecond

Those concepts appear to be denoting the same unit. The latter also violates the naming scheme (afaik).

--- 

http://qudt.org/vocab/unit/KiloGM-PER-SEC2

The label should most likely be "Kilogram *per* Second Squared" and not "Kilogram Second Squared" (see also http://qudt.org/vocab/unit/KiloGM-SEC2 )

---

http://qudt.org/vocab/unit/MegaTOE

Some of the properties here seem to be copied over from http://qudt.org/vocab/unit/TOE . However, they are not applicable. At least the following seem wrong to me right now: `qudt:conversionMultiplier`, `qudt:code`, `qudt:id`, `rdfs:label`, `skos:prefLabel` , `qudt:symbol`

---

http://qudt.org/vocab/unit/MilliARCSEC

`rdfs:label` and `skos:prefLabel` says "Mil Length" and "mil-length", but shouldn't those be exclusively for http://qudt.org/vocab/unit/MilLength ?

---

http://qudt.org/vocab/unit/KiloCAL-PER-CentiM2-DEG_C

No annotation makes any reference to the "Kilo" in "KiloCAL" or the 2 of "CentiM2*" of the IRI. I see multiple causes/solutions here:
* Fix all annotations to properly match up with the IRI.
* Remove the "2" from the IRI, which would merge it with the existing http://qudt.org/vocab/unit/KiloCAL-PER-CentiM-SEC-DEG_C 
* Remove both, the "2" and the "Kilo", from the IRI, which would bring the IRI in line with the annotations

---

Finally, I see two pairs of concepts, that denote different labels for the same unit, but have no apparent connection (e.g., `owl:sameAs` or `skos:closeMatch`):

http://qudt.org/vocab/unit/Dalton & http://qudt.org/vocab/unit/AMU
http://qudt.org/vocab/unit/GON & http://qudt.org/vocab/unit/GR

**Comment by jhodgesatmb** [comment]
Thank you for catching these. We will review and update.

Jack

**Comment by steveraysteveray** [comment]
Great catches! I have addressed all of them in PR #29, except that I believe the units GON and GR are distinct concepts.

**Comment by SirkoS** [comment]
> Great catches! I have addressed all of them in PR #29, except that I believe the units GON and GR are distinct concepts.

We had some doubts as well when writing our comparison paper at the time, but then took the SI brochure as an authoritative source. The [8th edition](https://www.bipm.org/utils/common/pdf/si_brochure_8.pdf) says on page 124 footnote (c) (emphasis added):

> The gon (**or grad, where grad is an alternative name for the gon**) is an alternative unit of plane
angle to the degree, defined as (π/200) rad.

Interestingly enough, I can not find some equivalent in the current [9th edition](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf) as of this year.

**Comment by steveraysteveray** [comment]
It seems there is some confusion between Gradian (which is as you define it), and Grade, which is the tangent of the angle. The latter is of course non-linear with respect to angle. Our unit:GR refers to Grade (the non-linear tangent). unit:GON refers to the Gradian, which also is called grad. Perhaps I should add the "grad" synonym to unit:GON so there is less confusion.
