### ISSUE TITLE
unit:PH needed

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#267]
pH - acidity

**Comment by steveraysteveray** [comment]
For now, this can be handled in the same way as Gross Tonnage (http://qudt.org/vocab/unit/GT), which has a non-linear relation to SI units, and thus cannot be adequately described using conversionMultiplier.
On our roadmap is to develop a more powerful conversion expression capability. Still to be tackled.

**Comment by dr-shorthair** [comment]
Fixed by #292
