### ISSUE TITLE
NVS P06 units that are missing from QUDT

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#268]
This list attached here https://github.com/qudt/qudt-public-repo/issues/268#issuecomment-721424132 shows items from the [NERC Vocabulary Service P06 vocabulary](vocab.nerc.ac.uk/collection/P06/current/) which do not have matches in QUDT, but could do since the elements are already there: 

Also see https://github.com/nvs-vocabs/P06/issues/18 

@gwemon

**Comment by dr-shorthair** [comment]
Here they are with Dimension vectors and conversion-multipliers

 QUDT item requested | Dimension vector | Numerator | Denominator | Multiplier | UCUM code 
 --- |  --- |  --- |  --- |  --- | --- 
 unit:BQ-SEC-PER-M3 | A0E0L-3I0M0H0T0D0 |  |  | 1 | Bq.s.m-3 
 unit:DeciBAR-PER-YR | A0E0L-1I0M1H0T-3D0 |  |  | 1.00E-18 | dbar.a-1 
 unit:DEG_C-PER-YR | A0E0L0I0M0H1T-1D0 |  |  | 1 | Cel.a-1 
 unit:DEG-PER-M | A0E0L-1I0M0H0T0D1 |  |  | 1 | deg.m-1 
 unit:DEG_C-KiloGM-PER-M2 | A0E0L-2I0M1H1T0D0 |  |  | 1 | Cel.kg.m-2 
 unit:K-PER-M | A0E0L-1I0M0H1T0D0 |  |  | 1 | K.m-1 
 unit:FemtoGM-PER-KiloGM | A0E0L0I0M0H0T0D1 | A0E0L0I0M1H0T0D0 | A0E0L0I0M1H0T0D0 | 1.00E-18 | fg.kg-1 
 unit:FemtoGM-PER-L | A0E0L-3I0M1H0T0D0 |  |  | 1.00E-15 | fg.L-1 
 unit:FemtoMOL-PER-KiloGM | A1E0L0I0M-1H0T0D0 |  |  | 1.00E-15 | fmol.kg-1 
 unit:GM-PER-CentiM2-YR | A0E0L-2I0M1H0T-1D0 |  |  | 3.17E-07 | g.cm-2.a-1 
 unit:HectoPA-PER-HR | A0E0L-1I0M1H0T-3D0 |  |  | 0.027777778 | hPa.h-1 
 unit:J-PER-CentiM2-DAY | A0E0L0I0M1H0T-3D0 |  |  | 0.115740741 | J.cm-2.d-1 
 unit:J-PER-KiloGM-K | A0E0L2I0M0H0T-3D0 |  |  | 1 | J.kg-1.K-1 
 unit:KiloGM-PER-KiloM2 | A0E0L-2I0M1H0T0D0 |  |  | 0.000001 | kg.km-2 
 unit:KiloGM-PER-M-HR | A0E0L-1I0M1H0T-1D0 |  |  | 0.000277778 | kg.m-1.h-1 
 unit:NanoMOL-PER-KiloGM | A1E0L0I0M-1H0T0D0 |  |  | 1.00E-09 | nmol.kg-1 
 unit:PicoMOL-PER-KiloGM | A1E0L0I0M-1H0T0D0 |  |  | 1.00E-12 | pmol.kg-1 
 unit:KiloGM2-PER-SEC2 | A0E0L0I0M2H0T-2D0 |  |  | 1 | kg2.s-2 
 unit:MicroMOL-PER-KiloGM | A1E0L0I0M-1H0T0D0 |  |  | 1.00E-06 | umol.kg-1 
 unit:K2 | A0E0L0I0M0H2T0D0 |  |  | 1 | K2 
 unit:KiloM-PER-DAY | A0E0L1I0M0H0T-1D0 |  |  | 0.011574074 | km.d-1 
 unit:KiloGM-PER-M-SEC | A0E0L-1I0M1H0T-1D0 |  |  | 1 | kg.m-1.s-1 
 unit:K-M2-PER-KiloGM-SEC | A0E0L2I0M-1H1T-1D0 |  |  | 1 | K.m2.kg-1.s-1 
 unit:K-M-PER-SEC | A0E0L1I0M0H1T-1D0 |  |  | 1 | K.m.s-1 
 unit:K-M | A0E0L1I0M0H1T0D0 |  |  | 1 | K.m 
 unit:K-PA-PER-SEC | A0E0L-1I0M1H1T-3D0 |  |  | 1 | K.Pa.s-1 
 unit:K-PER-M | A0E0L-1I0M0H1T0D0 |  |  | 1 | K.m-1 
 unit:K-PER-M2-SEC | A0E0L-2I0M0H1T-1D0 |  |  | 1 | kg.m-2.s-1 
 unit:K-PER-M3-SEC | A0E0L-3I0M0H1T-1D0 |  |  | 1 | kg.m-3.s-1 
 unit:K-SEC | A0E0L0I0M0H1T1D0 |  |  | 1 | K.s 
 unit:L-PER-MicroMOL | A-1E0L3I0M0H0T0D0 |  |  | 1000 | L.umol-1 
 unit:M2-PER-HZ-DEG | A0E0L2I0M0H0T1D-1 |  |  | 57.29577951 | m2.Hz-1.deg-1 
 unit:MOL-PER-M2-SEC-M | A1E0L-3I0M0H0T-1D0 |  |  | 1 | mol.m-2.s-1.m-1 
 unit:MOL-PER-M2-SEC | A1E0L-2I0M0H0T-1D0 |  |  | 1 | mol.m-2.s-1 
 unit:M2-SEC-PER-RAD | A0E0L2I0M0H0T1D-1 |  |  | 1 | m2.s.rad-1 
 unit:PER-M2-SEC | A0E0L-2I0M0H0T-1D0 |  |  | 1 | m-2.s-1 
 unit:MOL-PER-M2-SEC-M-SR | A1E0L-3I0M0H0T-1D-1 |  |  | 1 | mol.m-2.s-1.m-1.sr-1 
 unit:PER-M3-SEC | A0E0L-3I0M0H0T-1D0 |  |  | 1 | m-3.s-1 
 unit:MOL-PER-M2-SEC-SR | A1E0L-2I0M0H0T-1D-1 |  |  | 1 | mol.m-2.s-1.sr-1 
 unit:M4-PER-SEC | A0E0L4I0M0H0T-1D0 |  |  | 1 | m4.s-1 
 unit:MilliBQ-PER-GM | A0E0L0I0M-1H0T-1D0 |  |  | 1 | mBq.g-1 
 unit:MilliBQ-PER-M2-DAY | A0E0L-2I0M0H0T-2D0 |  |  | 1.16E-08 | mBq.m-2.d-1 
 unit:MilliBQ-PER-KiloGM | A0E0L0I0M-1H0T-1D0 |  |  | 0.001 | mBq.kg-1 
 unit:MilliMOL-PER-M3-DAY | A1E0L-3I0M0H0T-1D0 |  |  | 1.16E-08 | mmol.m-3.d-1 
 unit:MicroGM-PER-L-HR | A0E0L-3I0M1H0T-1D0 |  |  | 2.78E-10 | ug.L-1.h-1 
 unit:MilliGAL-PER-MO | A0E0L1I0M0H0T-3D0 |  |  | 3.80E-10 | mGal.mo-1 
 unit:MilliGM-PER-M2-HR | A0E0L-2I0M1H0T-1D0 |  |  | 2.78E-10 | mg.m-2.h-1 
 unit:MOL-PER-M2 | A1E0L-2I0M0H0T0D0 |  |  | 1 | mol.m-2 
 unit:MOL-PER-M3-SEC | A1E0L-3I0M0H0T-1D0 |  |  | 1 | mol.m-3.s-1 
 unit:MilliMOL-PER-M3 | A1E0L-3I0M0H0T0D0 |  |  | 0.001 | mmol.m-3 
 unit:MilliMOL-PER-MOL | A0E0L0I0M0H0T0D1 | A1E0L0I0M0H0T0D0 | A1E0L0I0M0H0T0D0 | 0.001 | mmol.mol-1 
 unit:MilliMOL-PER-M2 | A1E0L-2I0M0H0T0D0 |  |  | 0.001 | mmol.m-2 
 unit:MOL-PER-GM-HR | A1E0L0I0M-1H0T-1D0 |  |  | 0.277777778 | mol.g-1.h-1 
 unit:MOL-PER-MOL | A0E0L0I0M0H0T0D1 | A1E0L0I0M0H0T0D0 | A1E0L0I0M0H0T0D0 | 1 | mol.mol-1 
 unit:M-PER-YR | A0E0L1I0M0H0T-1D0 |  |  | 3.17E-08 | m.a-1 
 unit:MilliRAD_R-PER-HR | A0E0L2I0M0H0T-3D0 |  |  | 2.78E-07 | mRAD.h-1 
 unit:MilliL-PER-M2-DAY | A0E0L1I0M0H0T-1D0 |  |  | 1.16E-11 | mL.m-2.d-1 
 unit:MilliS-PER-M | A0E2L-4I0M-1H0T3D0 |  |  | 0.001 | mS.m-1 
 unit:MilliW-PER-M2-NanoM | A0E0L-1I0M1H0T-3D0 |  |  | 1000000 | mW.m-2.nm-1 
 unit:MilliW-PER-M2-NanoM-SR | A0E0L-1I0M1H0T-3D-1 |  |  | 1000000 | mW.m-2.nm-1.sr-1 
 unit:MilliW-PER-CentiM2-MicroM-SR | A0E0L-1I0M1H0T-3D-1 |  |  | 10000000 | mW.cm-2.um-1.sr-1 
 unit:NUM-PER-HectoGM | A0E0L0I0M-1H0T0D1 |  |  | 10 | {#}.hg-1 
 unit:NUM-PER-MilliGM | A0E0L0I0M-1H0T0D1 |  |  | 1000000 | {#}.mg-1 
 unit:N-PER-M3 | A0E0L-2I0M1H0T-2D0 |  |  | 1 | N.m-3 
 unit:NUM-PER-HA | A0E0L-2I0M0H0T0D1 |  |  | 1000000 | {#}.har-1 
 unit:NanoMOL-PER-CentiM3-HR | A1E0L-3I0M0H0T-1D0 |  |  | 2.78E-07 | nmol.cm-3.h-1 
 unit:NanoMOL-PER-MicroGM-HR | A1E0L0I0M-1H0T-1D0 |  |  | mol.kg-1.s-1  | nmol.ug-1.h-1 
 unit:NanoMOL-PER-MicroMOL-DAY | A0E0L0I0M0H0T-1D1 |  |  | 1.16E-08 | nmol.umol-1.d-1 
 unit:NanoMOL-PER-MicroMOL | A0E0L0I0M0H0T0D1 | A1E0L0I0M0H0T0D0 | A1E0L0I0M0H0T0D0 | 0.001 | nmol.umol-1 
 unit:NUM-PER-HR | A0E0L0I0M0H0T-1D1 |  |  | 0.000277778 | {#}.h-1 
 unit:NUM-PER-M | A0E0L-1I0M0H0T0D1 |  |  | 1 | {#}.m-1 
 unit:NUM-PER-KiloM2 | A0E0L-2I0M0H0T0D1 |  |  | 0.000001 | {#}.km-2 
 unit:NanoMOL-PER-M2-DAY | A1E0L-2I0M0H0T-1D0 |  |  | 1.16E-14 | nmol.m-2.d-1 
 unit:PA-M-PER-SEC2 | A0E0L0I0M1H0T-4D0 |  |  | 1 | Pa.m.s-2 
 unit:PA-M-PER-SEC | A0E0L0I0M1H0T-3D0 |  |  | 1 | Pa.m.s-1 
 unit:PA-M | A0E0L0I0M1H0T-2D0 |  |  | 1 | Pa.m 
 unit:PER-GM | A0E0L0I0M-1H0T0D0 |  |  | 1000 | g-1 
 unit:PicoGM-PER-KiloGM | A0E0L0I0M0H0T0D1 | A0E0L0I0M1H0T0D0 | A0E0L0I0M1H0T0D0 | 1.00E-15 | pg.kg-1 
 unit:PicoGM-PER-GM | A0E0L0I0M0H0T0D1 | A0E0L0I0M1H0T0D0 | A0E0L0I0M1H0T0D0 | 1.00E-12 | pg.g-1 
 unit:PicoGM-PER-L | A0E0L-3I0M1H0T0D0 |  |  | 1.00E-12 | pg.L-1 
 unit:PicoMOL-PER-L-DAY | A0E0L-3I0M1H0T-1D0 |  |  | 1.16E-14 | pmol.L-1.d-1 
 unit:PER-M-SEC | A0E0L-1I0M0H0T-1D0 |  |  | 1 | m-1.s-1 
 unit:PER-MilliSEC | A0E0L0I0M0H0T-1D0 |  |  | 1000 | ms-1 
 unit:PER-M-SR | A0E0L-1I0M0H0T0D-1 |  |  | 1 | m-1.sr-1 
 unit:PER-PA-SEC | A0E0L1I0M-1H0T1D0 |  |  | 1 | Pa-1.s-1 
 unit:PA2-PER-SEC2 | A0E0L-2I0M2H0T-6D0 |  |  | 1 | Pa2.s-2 
 unit:PER-SR | A0E0L0I0M0H0T0D-1 |  |  | 1 | sr-1 
 unit:PER-MicroMOL-L | A-1E0L-3I0M0H0T0D0 |  |  | 1000000000 | umol-1.L-1 
 unit:PicoW-PER-CentiM2-L | A0E0L-3I0M1H0T-3D0 |  |  | 0.00001 | pW.cm-2.L-1 
 unit:SEC-PER-M | A0E0L-1I0M0H0T1D0 |  |  | 1 | s.m-1 
 unit:m2-PER-GM | A0E0L2I0M-1H0T0D0 |  |  | 1000 | m2.g-1 
 unit:CentiM2-PER-CentiM3 | A0E0L-1I0M0H0T0D0 |  |  | 100 | cm2.cm-3 
 unit:MicroATM | A0E0L-1I0M1H0T-2D0 |  |  | 0.101325 | uatm 
 unit:BQ-PER-L | A0E0L-3I0M0H0T-1D0 |  |  | 1000 | Bq.L-1 
 unit:MicroM3-PER-M3 | A0E0L0I0M0H0T0D1 | A0E0L3I0M0H0T0D0 | A0E0L3I0M0H0T0D0 | 1.00E-18 | um3.m-3 
 unit:CentiM-PER-KiloYR | A0E0L1I0M0H0T-1D0 |  |  | 3.17E-13 | cm.ka-1 
 unit:NUM-PER-NanoL | A0E0L-3I0M0H0T0D1 |  |  | 1E+12 | {#}.nL-1 
 unit:NUM-PER-L | A0E0L-3I0M0H0T0D1 |  |  | 1000 | {#}.L-1 
 unit:NUM-PER-SEC | A0E0L0I0M0H0T-1D1 |  |  | 1 | {#}.s-1 
 unit:K2-PER-SEC | A0E0L0I0M0H2T-1D0 |  |  | 1 | K2.s-1 
 unit:NUM-PER-MicroL | A0E0L-3I0M0H0T0D1 |  |  | 1000000000 | {#}.uL-1 
 unit:MicroM3-PER-MilliL | A0E0L0I0M0H0T0D1 | A0E0L3I0M0H0T0D0 | A0E0L3I0M0H0T0D0 | 1.00E-12 | um3.mL-1 
 unit:MilliGM-PER-M3-DAY | A0E0L-3I0M1H0T-1D0 |  |  | 1.16E-11 | mg.m-3.d-1 
 unit:MilliGM-PER-M2-DAY | A0E0L-2I0M1H0T-1D0 |  |  | 1.16E-11 | mg.m-2.d-1 
 unit:MicroGM-PER-GM | A0E0L0I0M0H0T0D1 | A0E0L0I0M1H0T0D0 | A0E0L0I0M1H0T0D0 | 0.000001 | ug.g-1 
 unit:MilliGM-PER-M3-HR | A0E0L-3I0M1H0T-1D0 |  |  | 2.78E-10 | mg.m-3.h-1 
 unit:MicroGM-PER-M3-HR | A0E0L-3I0M1H0T-1D0 |  |  | 2.78E-13 | ug.m-3.h-1 
 unit:PicoGM | A0E0L0I0M1H0T0D0 |  |  | 1.00E-15 | pg 
 unit:MicroGAL-PER-M | A0E0L0I0M0H0T-2D0 |  |  | 1.00E-08 | uGal.m-1 
 unit:MicroMOL-PER-M2-SEC | A1E0L-2I0M0H0T-1D0 |  |  | 0.000001 | umol.m-2.s-1 
 unit:MilliBQ-PER-L | A0E0L-3I0M0H0T-1D0 |  |  | 1.00E+00 | mBq.L-1 
 unit:MicroM3 | A0E0L3I0M0H0T0D0 |  |  | 1.00E-18 | um3 
 unit:MilliMOL-PER-M2-DAY | A1E0L-2I0M0H0T-1D0 |  |  | 1.16E-08 | mmol.m-2.d-1 
 unit:MicroMOL-PER-M2-HR | A1E0L-2I0M0H0T-1D0 |  |  | 2.78E-10 | umol.m-2.h-1 
 unit:M2-PER-HZ | A0E0L2I0M0H0T1D0 |  |  | 1 | m2.Hz-1 
 unit:MicroM-PER-L-DAY | A0E0L-2I0M0H0T-1D0 |  |  | 1.16E-08 | um.L-1.d-1 
 unit:MicroMOL-PER-L-HR | A1E0L-3I0M0H0T-1D0 |  |  | 2.78E-07 | umol.L-1.h-1 
 unit:PER-M-NanoM-SR | A0E0L-2I0M0H0T0D-1 |  |  | 1000000000 | m-1.nm-1.sr-1 
 unit:PER-M-NanoM | A0E0L-2I0M0H0T0D0 |  |  | 1000000000 | m-1.nm-1 
 unit:MicroMOL-PER-MOL | A0E0L0I0M0H0T0D1 | A1E0L0I0M0H0T0D0 | A1E0L0I0M0H0T0D0 | 0.000001 | umol.mol-1 
 ~unit:M2-PER-GM | A0E0L2I0M-1H0T0D0 |  |  | 1000 | m2.g-1{dry} 
 unit:M2-HZ | A0E0L2I0M0H0T-1D0 |  |  | 1 | m2.Hz 
 unit:M2-HZ2 | A0E0L2I0M0H0T-2D0 |  |  | 1 | m2.Hz2 
 unit:M2-HZ3 | A0E0L2I0M0H0T-3D0 |  |  | 1 | m2.Hz3 
 unit:M2-HZ4 | A0E0L2I0M0H0T-4D0 |  |  | 1 | m2.Hz4 
 unit:M2-PER-HZ2 | A0E0L2I0M0H0T2D0 |  |  | 1 | m2.Hz-2 
 unit:MicroMOL-PER-MicroMOL-DAY | A0E0L0I0M0H0T-1D1 |  |  | 1.15741E-05 | umol.umol-1.d-1 
 unit:NUM-PER-HR | A0E0L0I0M0H0T-1D1 |  |  | 0.000277778 | {#}.h-1 
 unit:NanoBQ-PER-L | A0E0L-3I0M0H0T-1D0 |  |  | 0.000001 | nBq.L-1 
 unit:NUM-PER-M2-DAY | A0E0L-2I0M0H0T-1D1 |  |  | 1.15741E-05 | {#}.m-2.d-1 
 unit:NanoGM-PER-L | A0E0L-3I0M1H0T0D0 |  |  | 1.00E-09 | ng.L-1 
 unit:NanoGM-PER-DAY | A0E0L0I0M1H0T-1D0 |  |  | 1.16E-17 | ng.d-1 
 unit:NanoMOL-PER-L-DAY | A1E0L-3I0M0H0T-1D0 |  |  | 1.16E-11 | nmol.L-1.d-1 
 unit:NanoMOL-PER-L-HR | A1E0L-3I0M0H0T-1D0 |  |  | 2.78E-10 | nmol.L-1.h-1 
 unit:NUM-PER-GM | A0E0L0I0M-1H0T0D1 |  |  | 1000 | {#}.g-1 
 unit:NanoGM | A0E0L0I0M1H0T0D0 |  |  | 1.00E-12 | ng 
 unit:NanoGM-PER-MicroL | A0E0L-3I0M1H0T0D0 |  |  | 0.001 | ng.uL-1 
 unit:PicoA-PER-MicroMOL-L | A-1E1L-3I0M0H0T0D0 |  |  | 0.001 | pA.umol-1.L-1 
 unit:DEG_C-PER-M | A0E1L-1I0M0H1T0D0 |  |  | 1 | Cel.m-1 
 unit:PERCENT-PER-DAY | A0E0L0I0M0H0T-1D1 |  |  | 1.15741E-05 | %.d-1 
 unit:PERCENT-PER-HR | A0E0L0I0M0H0T-1D1 |  |  | 0.000277778 | %.h-1 
 unit:PERCENT-PER-WK | A0E0L0I0M0H0T-1D1 |  |  | 1.65344E-06 | %.wk-1 
 unit:FemtoMOL-PER-L | A1E0L-3I0M0H0T0D0 |  |  | 1.00E-12 | fmol.L-1 
 unit:PicoMOL-PER-M3 | A1E0L-3I0M0H0T0D0 |  |  | 1.00E-12 | pmol.m-3 
 unit:PicoMOL-PER-M2-DAY | A1E0L-3I0M0H0T-1D0 |  |  | 1.16E-17 | pmol.m-2.d-1 
 unit:PicoMOL-PER-L-HR | A1E0L-3I0M0H0T-1D0 |  |  | 2.78E-13 | pmol.L-1.h-1 
 unit:PicoMOL-PER-L | A1E0L-3I0M0H0T0D0 |  |  | 1.00E-09 | pmol.L-1 
 unit:NUM-PER-M3 | A0E0L-3I0M0H0T0D1 |  |  | 1 | {#}.m-3 
 unit:NUM-PER-M2 | A0E0L-2I0M0H0T0D1 |  |  | 1 | {#}.m-2 
 unit:PERCENT-PER-M | A0E0L-1I0M0H0T0D1 |  |  | 1 | %.m-1 
 unit:MicroMOL-PER-L | A1E0L-3I0M0H0T0D0 |  |  | 0.001 | umol.L-1 
 unit:PER-SEC2 | A0E0L0I0M0H0T-2D0 |  |  | 1 | s-2 
 unit:PPTH-PER-HR | A0E0L0I0M0H0T-1D1 |  |  | 2.78E-07 | [ppth].h-1 
 unit:PicoMOL-PER-M3-SEC | A1E0L-3I0M0H0T-1D0 |  |  | 1.00E-12 | pmol.m-3.s-1 
 unit:PicoMOL-PER-M-W-SEC | A1E0L-3I0M-1H0T2D0 |  |  | 1.00E-12 | pmol.m-1.W-1.s-1 
 unit:MicroM-PER-MilliL | A0E0L-2I0M0H0T0D0 |  |  | 0.000001 | um2.mL-1 
 ~unit:PPTR | A0E0L0I0M0H0T0D1 |  |  | 1.00E-12 | [pptr]{vol} 
 unit:MicroBQ-PER-L | A0E0L-3I0M0H0T-1D0 |  |  | 0.001 | uBq.L-1 
 unit:MicroGM-PER-M2-DAY | A0E0L-2I0M1H0T-1D0 |  |  | 1.16E-14 | ug.m-2.d-1 
 <https://github.com/qudt/qudt-public-repo/issues/267> |  |  |  |  | [pH] 
 unit:MicroMOL-PER-M2-DAY | A1E0L-2I0M0H0T-1D0 |  |  | 1.16E-11 | umol.m-2.d-1 
 unit:NUM-PER-CentiM-KiloYR | A0E0L-1I0M0H0T-1D1 |  |  | 3.17E-07 | {#}.cm-2.ka-1 
 unit:MicroBQ-PER-KiloGM | A0E0L0I0M-1H0T-1D0 |  |  | 0.000001 | uBq.kg-1 
 unit:W-PER-M2-NanoM | A0E0L-1I0M1H0T-3D0 |  |  | 1000000000 | W.m-2.nm-1 
 unit:W-PER-M2-NanoM-SR | A0E0L-1I0M1H0T-3D-1 |  |  | 1000000000 | W.m-2.nm-1.sr-1 
 unit:W-PER-M | A0E0L1I0M1H0T-3D0 |  |  | 1 | W.m-1 
 unit:W-PER-M2-M | A0E0L-1I0M1H0T-3D0 |  |  | 1 | W.m-2.m-1 
 unit:W-PER-M2-M-SR | A0E0L-1I0M1H0T-3D-1 |  |  | 1 | W.m-2.m-1.sr-1 
 unit:W-M-PER-M2-SR | A0E0L1I0M1H0T-3D-1 |  |  | 1 | W.m-2.m.sr-1 
 unit:W-SEC-PER-M2 | A0E0L0I0M1H0T-2D0 |  |  | 1 | W.s.m-2 

@gwemon Progress!

**Comment by dr-shorthair** [comment]
@steveraysteveray I think this is minimum info needed for some new Units ?

**Comment by dr-shorthair** [comment]
And now with Labels and Definitions taken directly from P06. 
I've added some QuantityKind entries, but many not available. 

[qudt-requests.xlsx](https://github.com/qudt/qudt-public-repo/files/5462526/qudt-requests.xlsx)

**Comment by dr-shorthair** [comment]
Updated to fix misunderstanding of D value in Dimension Vector - #270 
[qudt-requests.xlsx](https://github.com/qudt/qudt-public-repo/files/5478648/qudt-requests.xlsx)

**Comment by steveraysteveray** [comment]
Simon,
Once we're less distracted with the future of democracy over here, I will be focusing on all your hard work so that we can add these units, and come to some agreement on the quantity/quantitykind question!

**Comment by dr-shorthair** [comment]
Added a couple more: 
[qudt-requests.xlsx](https://github.com/qudt/qudt-public-repo/files/5484599/qudt-requests.xlsx)

For sure I did not expect these to be processed immediately. Just trying to make it as easy as possible for us to knit together the various systems ;-)

**Comment by dr-shorthair** [comment]
FYI recent additions to NVS P06 have added link to QUDT as a matter of course - 
https://github.com/nvs-vocabs/P06/issues/19 
http://vocab.nerc.ac.uk/collection/P06/current/MGRM/

**Comment by steveraysteveray** [comment]
Wonderful!

**Comment by dr-shorthair** [comment]
A few corrections 
[qudt-requests.xlsx](https://github.com/qudt/qudt-public-repo/files/5541903/qudt-requests.xlsx)

**Comment by steveraysteveray** [comment]
Simon, I did some hacking to bludgeon your spreadsheet above into triples that conform to our structure. 😄 
However, along the way I see a few suspicious entries, such as
 BQ-SEC-PER-M3 having a QuantityKind of ActivityConcentration, since all the other units with that QuantityKind have a different dimensionality:
![image](https://user-images.githubusercontent.com/1130189/99319503-7f9c1f00-281e-11eb-840a-c3c9b1e3b939.png)

So I invite you to take a look at the [srr-P06-imports](https://github.com/qudt/qudt-public-repo/tree/srr-P06-imports) branch and let's quality-check it. Also, as you know from your spreadsheet, many of the units are missing QuantityKind values altogether.

**Comment by dr-shorthair** [comment]
The QuantityKind column is very dubious throughout. I just threw a few in where I thought I could find existing QKs that fit, but needs to be reviewed. Probably we should bring in @gwemon 

That one is definitely incorrect - looks like it was mis-pasted and should be in the line above. 
Probably it should be AbsoluteActivity

**Comment by gwemon** [comment]
I'll have a look later on this week.

**Comment by dr-shorthair** [comment]
Suggest just working from the spreadsheet.

**Comment by dr-shorthair** [comment]
@steveraysteveray I converted the spreadsheet in SKOS-PLAY! format (https://labs.sparna.fr/skos-play/convert ) which makes it easy to generate the TTL - 
[qudt-requests.xlsx](https://github.com/qudt/qudt-public-repo/files/5579065/qudt-requests.xlsx)

[P06-additions.ttl.txt](https://github.com/qudt/qudt-public-repo/files/5579066/P06-additions.ttl.txt)

**Comment by dr-shorthair** [comment]
Files also in this fork https://github.com/dr-shorthair/qudt-public-repo/tree/P06/community/NVS-P06 

This SKOS-Play! format seems pretty easy to work with. 
Might be a good general submission template?

**Comment by steveraysteveray** [comment]
Very interesting! About a week ago I discovered SHACL-Play, from the same people.  https://shacl-play.sparna.fr/
I'll check out SKOS-Play.

**Comment by dr-shorthair** [comment]
Maybe not so much 'bludgeoning' required ;-)
