### ISSUE TITLE
LaTeX rendering not working for all values

### ISSUE THREAD

**Issue by EvaIbarra** [qudt/qudt-public-repo#283]
Some property values (e.g. symbol at http://www.qudt.org/edg/tbl/qudt_units.editor#unit:PlanckEnergy) are supposed to be render as LaTeX as they are written in TeX notation, but it is not the case. It also happens for some dcterms:description values (e.g. http://www.qudt.org/edg/tbl/qudt_units.editor#unit:AMU).

**Comment by dr-shorthair** [comment]
You say 'some'. Could you list the problematic ones.

**Comment by steveraysteveray** [comment]
Yes, thanks for mentioning these. We're aware that a number of our units slipped through the cracks regarding the use of TeX. I'm assigning myself this to go back and do a little more cleanup.

**Comment by steveraysteveray** [comment]
Fixed the ones identified.
