### ISSUE TITLE
Why qk:Density AND qk:MassDensity ?

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#296]
http://qudt.org/vocab/quantitykind/Density
http://qudt.org/vocab/quantitykind/MassDensity

At least there should be a pointer between them?

**Comment by steveraysteveray** [comment]
Interesting comment. I'm currently cleaning up a number of potentially ambiguous quantity kind concepts, such as:
Angle versus PlaneAngle versus SolidAngle. In cases like this, we are opting for the "common" interpretation of the term, such that Angle is defined to mean the 2-D angle, SolidAngle means the 3-D angle, and PlaneAngle will remain as a duplicate for Angle in case very precise people are looking for the 2-D angle. :)
The issue of duplicate units just came up in Issue #302 as well.

Regarding Density, my understanding is most people think of mass per volume when they encounter that term (i.e. MassDensity), so we will likely handle this the same way (with a link between Density and MassDensity, the approach mentioned in Issue #302). The other interpretations, such as MolarDensity, etc. will be spelled out as distinct qnames.
