### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by jmkeil** [qudt/qudt-public-repo#304]
Using a [comparison of unit ontologies with ABECTO](https://github.com/fusion-jena/abecto-unit-ontology-comparison) I became aware that the following units miss symbols:
* [ ] http://qudt.org/vocab/unit/AU: `AU`
* [ ] http://qudt.org/vocab/unit/L: `l` (in addition to `L`)

**Comment by steveraysteveray** [comment]
Noted. Also, see my note on #305

**Comment by steveraysteveray** [comment]
Unless somebody sneaked in and added it, I find AU already has the symbol.
I have added "l" for the Litre, in addition to "L".

Thanks again.
Handled in PR #318
