### ISSUE TITLE
Wrong UCUM codes

### ISSUE THREAD

**Issue by jmkeil** [qudt/qudt-public-repo#306]
During analysis of the results of a [comparison of unit ontologies with ABECTO](https://github.com/fusion-jena/abecto-unit-ontology-comparison) I became aware that the following units have wrong UCUM codes:
* [ ] http://qudt.org/vocab/unit/PER-MilliM3: `m-3`
* [ ] http://qudt.org/vocab/unit/OHM_Ab: `nOhm`
* [ ] http://qudt.org/vocab/unit/Hundredweight_UK: `cwt_av`

**Comment by dr-shorthair** [comment]
Thanks - 
- http://qudt.org/vocab/unit/PER-MilliM3: m-3 - should be `mm-3`
- http://qudt.org/vocab/unit/OHM_Ab: `nOhm` - _I believe this one is correct ( Abohm = nano-Ohm)_
- http://qudt.org/vocab/unit/Hundredweight_UK: cwt_avmm-3 - should be `[lcwt_av]`
