### ISSUE TITLE
Duplicated units - Hundredweight_UK=CWT_LONG Hundredweight_US=CWT_SHORT

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#309]
- Hundredweight_UK=CWT_LONG 
- Hundredweight_US=CWT_SHORT
Which is preferred?

**Comment by dr-shorthair** [comment]
See #302

**Comment by steveraysteveray** [comment]
Simon, these two are different units, right? So there are two pairs of units, with each pair having two alternate (duplicate) qnames. It looks like the Long one needs a conversion multiplier though.

**Comment by dr-shorthair** [comment]
yes, two pairs, but had already been mentioned in #302 so I closed this one.
