### ISSUE TITLE
unit:C4-M4-PER-J3 has incorrect conversionOffset

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#326]
http://qudt.org/vocab/unit/C4-M4-PER-J3 is showing `qudt:conversionOffset 1.0` which appears incorrect.

**Comment by steveraysteveray** [comment]
Good catch! I'll include the fix next time I do a PR.

**Comment by dr-shorthair** [comment]
I found it when I looked for all instances of `qudt:conversionOffset`. 
They are extremely rare in practice, since the catalogue is primarily for ratio scales, not interval scales.
