### ISSUE TITLE
Update unit submission guidelines

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#329]
The section https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines#required-unit-properties should be updated. Multipliers and offsets should be decimals; offset is optional as it is only required for interval scales (not ratio scales); quantity-kind is recommended but not mandatory; and I've modified the example so it is a non-trivial case instead of one of the base units: 

# Required unit properties

The absolute minimum set of required properties are shown in the following example:
```
unit:MilliM
  rdf:type qudt:Unit ;
  rdfs:label "Millimetre"@en ;
  rdfs:label "Millimeter"@en-us ;
  qudt:conversionMultiplier 0.001 ;
  qudt:conversionOffset 0.0 ; # mandatory for interval scales only
  qudt:hasDimensionVector qkdv:A0E0L1I0M0H0T0D0 ;
  qudt:plainTextDescription "The millimetre (International spelling as used by the International Bureau of Weights and Measures) or millimeter (American spelling) (SI unit symbol mm) is a unit of length in the metric system, equal to one thousandth of a metre, which is the SI base unit of length. It is equal to 1000 micrometres or 1000000 nanometres. A millimetre is equal to exactly 5/127 (approximately 0.039370) of an inch."^^rdf:HTML ;
  qudt:hasQuantityKind quantitykind:Length ; # recommended but not mandatory
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
.
```
In other words,

- `rdf:type` . qudt:Unit, and optionally any other qudt class names in the Unit class hierarchy
- `rdfs:label` . A human-readable label.
- `qudt:conversionMultiplier` . The multiplier to convert quantities using this unit to quantities using the SI unit for this quantity kind
- `qudt:conversionOffset` (optional) . The offset used to convert units for interval scales to the SI unit of this quantity kind
- `qudt:hasDimensionVector` . The dimension vector associated with this unit
- `qudt:plainTextDescription` . Some sort of description
- `qudt:hasQuantityKind` . The quantity kind(s) for this unit. They should all be of the same dimensionality. Also, see appropriateUnit
- `rdfs:isDefinedBy` . The graph this unit is defined in (which by convention is uniquely associated with the containing file)

**Comment by steveraysteveray** [comment]
The problem with making hasQuantityKind recommended rather than mandatory is that the unit will not show up in a query for qudt:appropriateUnit unless the unit points to some quantitykind in the skos:broader hierarchy. Because this therefore reduces the functionality of applications (for example, I'm working in a standards committee that uses qudt:appropriateUnit to validate units chosen by applications), I am loathe to relax that requirement. So for the time being, I'm happy to adopt all the other suggestions you make!

**Comment by jhodgesatmb** [comment]
QUDT has always had Unit point to QuantityKind; it is part of the quantity triad pattern. I would want to know why it should be optional rather than why it should be required.

Jack Hodges, Ph.D.
Arbor Studios

**Comment by dr-shorthair** [comment]
OK - I see why you need quantityKind in general. Revised proposal: 

The section https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines#required-unit-properties should be updated. Multipliers and offsets should be decimals; offset is optional as it is only required for interval scales (not ratio scales); quantity-kind is recommended but not mandatory; and I've modified the example so it is a non-trivial case instead of one of the base units: 

# Required unit properties

The absolute minimum set of required properties are shown in the following example:
```
unit:MilliM
  rdf:type qudt:Unit ;
  rdfs:label "Millimetre"@en ;
  rdfs:label "Millimeter"@en-us ;
  qudt:conversionMultiplier 0.001 ;
  qudt:conversionOffset 0.0 ; # mandatory for interval scales only
  qudt:hasDimensionVector qkdv:A0E0L1I0M0H0T0D0 ;
  qudt:plainTextDescription "The millimetre (International spelling as used by the International Bureau of Weights and Measures) or millimeter (American spelling) (SI unit symbol mm) is a unit of length in the metric system, equal to one thousandth of a metre, which is the SI base unit of length. It is equal to 1000 micrometres or 1000000 nanometres. A millimetre is equal to exactly 5/127 (approximately 0.039370) of an inch."^^rdf:HTML ;
  qudt:hasQuantityKind quantitykind:Length ; 
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
.
```
In other words,

- `rdf:type` . qudt:Unit, and optionally any other qudt class names in the Unit class hierarchy
- `rdfs:label` . A human-readable label.
- `qudt:conversionMultiplier` . The multiplier to convert quantities using this unit to quantities using the SI unit for this quantity kind
- `qudt:conversionOffset` (optional) . The offset used to convert units for interval scales to the SI unit of this quantity kind
- `qudt:hasDimensionVector` . The dimension vector associated with this unit
- `qudt:plainTextDescription` . Some sort of description
- `qudt:hasQuantityKind` . The quantity kind(s) for this unit. They should all have the same dimension vector as the unit. Also, see appropriateUnit
- `rdfs:isDefinedBy` . The graph this unit is defined in (which by convention is uniquely associated with the containing file)

**Comment by steveraysteveray** [comment]
The wiki has been updated. Note that the additional recommended properties section still uses unit:M as the example. I didn't go in and update that.
