### ISSUE TITLE
New unit requests for eReefs

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#339]
Required for eReefs (Australia) 

- DEG_C-WK
- ~~GM-N-PER-M2~~ Nitrogen not Newtons!
- GM-PER-M2
- MOL-PER-M2-DAY 
- ~~MilliGM-N-PER-M3~~ Nitrogen not Newtons!
- MilliGM-M3 - checking this one
- MilliGM-PER-M2-SEC
- MilliGM-PER-M3-SEC
- PSU - or PSS-78 https://unesdoc.unesco.org/ark:/48223/pf0000047932_eng 

I'll prepare the definitions and make a PR

**Comment by steveraysteveray** [comment]
Wonderful! Thanks for that.
Steve

**Comment by dr-shorthair** [comment]
Completed by #340
