### ISSUE TITLE
Incorrect release number in TTL file

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#346]
Release 2.1.8 was just announced. 
However, in the `vaem:GMD_QUDT-UNITS-ALL` resource in https://github.com/qudt/qudt-public-repo/blob/master/vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl, the number is still **2.1.2** in three places.

**Comment by steveraysteveray** [comment]
You are correct. I need to finish double-checking that changing any of them doesn't break my publishing scripts. I know that vaem:graphTitle is used. It shouldn't, of course, but I need to check.
I will fix them!
(Also, I neglected to update to 2.1.8 in the schema metadata!)

**Comment by steveraysteveray** [comment]
OK. I have fixed the metadata so that it says 2.1.8 in all the right places. The updated files are on our web page, qudt.org and on this repo. I'm not going to do another github Release, but I'll be careful to pay attention to this in Release 2.1.9!

**Comment by dr-shorthair** [comment]
Did you merge it yet?

**Comment by steveraysteveray** [comment]
Yes


 
- Steve
