### ISSUE TITLE
Combine Unit with conversion factor

### ISSUE THREAD

**Issue by niklassiemer** [qudt/qudt-public-repo#362]
Hello, 
I have a question to the units in 'special' cases. E.g. in the theoretical chemistry community is it not uncommon to specify units like
'eV/Angstrom' for energy convergence thresholds which are rather uncommon elsewhere. In some cases one also likes to have another scale for some axis and measure in 'some factor times a well defined unit'. Is there a way to combine units and such prefactor in a well defined way to be used in such cases or would one need to specify each unit individually?

**Comment by steveraysteveray** [comment]
We welcome domain-specific units, and encourage you to submit their definitions in as much detail as you can. eV/Angstrom sounds like a fine example. The URL would be unit:EV-PER-ANGSTROM. Please take a look [here](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines) for details on submissions. 

Regarding your need for 'some factor times a well defined unit', if the factor is a power of 10, hopefully you can use one of the predefined prefixes. If it is some wacky other factor, or a changing factor, you might be best doing that representation inside your application. It's really a judgment call as to how widespread your use cases are, I suppose.

Looking forward to getting your input!

**Comment by dr-shorthair** [comment]
Perhaps also worth clarifying that the QUDT distribution is built on static representations of each unit-of-measurement. Unlike generative systems (e.g. UCUM) if it is not in the catalog, then it doesn't exist. All the element required to build more or less any unit-of-measurement are available in QUDT, but yes, you do have to define each one explicitly.

**Comment by niklassiemer** [comment]
Thanks a lot for the clarification!
