### ISSUE TITLE
convert CSV into RDF using QUDT

### ISSUE THREAD

**Issue by chunhualiao** [qudt/qudt-public-repo#365]
Hi, are there any tools which can automatically convert CSV files into RDF using QUDT?   How do QUDT people expect users to apply QUDT to large scale data?

**Comment by steveraysteveray** [comment]
Yes, there are tools to do what you ask. Many of the ontology editing
environments do that. See, for example, the TopBraid Composer
<https://www.topquadrant.com/products/topbraid-composer/>tool offered by
TopQuadrant.

QUDT is not a tool, it is a set of ontologies. Think of it as a set of
reference data. We do deliver the QUDT ontologies using the EDG tool
(kindly donated by TopQuadrant to QUDT.org). If you would like to explore
using our installed EDG tool for your needs, please contact us at
info@qudt.org.

Steve

**Comment by chunhualiao** [comment]
Thanks for your quick response.  While I am reading about the EDG tool, would you recommend any open-source tools also?

**Comment by steveraysteveray** [comment]
I kind of like SKOS Play! (https://skos-play.sparna.fr/play/convert), which, despite its name, isn't limited to SKOS.

**Comment by chunhualiao** [comment]
SKOS looks very interesting. Is there an example speedsheet(or CSV file) using QUDT which can be used to test it?

**Comment by steveraysteveray** [comment]
You appear to be asking about two different things:
1. How to convert between CSV/spreadsheets and RDF
2. Learning more about QUDT and units of measure

I'm happy to address #2, but I'm not the best person to help you with #1.

**Comment by chunhualiao** [comment]
I more or less know how to manually use QUDT based on existing documentation.  To apply it to large datasets (mostly tabular data) needs automation. I will search more. Thanks for your help so far.

**Comment by chunhualiao** [comment]
Ok. I just learned how to use sparql's construct query can handle this.
