### ISSUE TITLE
Prefix namespaces with version string

### ISSUE THREAD

**Issue by ktk** [qudt/qudt-public-repo#366]
When we started looking at qudt quite some time ago we had:

* prefix: http://qudt.org/vocab/prefix/ 

Now we have:
* prefix: http://qudt.org/2.1/vocab/prefix/

Was that the idea?

**Comment by steveraysteveray** [comment]
Wow! Definitely an error on my part, introduced it seems back in July.
I will put it back without the version number in my next edit.

Thanks for catching that.
