### ISSUE TITLE
http://www.qudt.org/pages/QUDToverviewPage.html contains dead links?!

### ISSUE THREAD

**Issue by DrMaggie** [qudt/qudt-public-repo#368]
My apologies if this isn't the right place to report this issue... 

When I visit http://www.qudt.org/pages/QUDToverviewPage.html and look at the graphs illustrated there, I note that the nominally clickable links to learn more about the various graph components are broken. 

An example: in the graph for QuantityKind (section 1.2) the links for qudt:QuantityKind, qudt:Quantity etc all return "Not found" messages. In the case of qudt:QuantityKind, the URL is http://www.qudt.org/pages/swp?_base=http%3A//rdfex.org/withImports%3Furi%3Dhttp%3A//qudt.org/2.1/collection/docgen&_resource=http%3A//qudt.org/schema/qudt/QuantityKind, and for qudt:Quantity the corresponding URL is http://www.qudt.org/pages/swp?_base=http%3A//rdfex.org/withImports%3Furi%3Dhttp%3A//qudt.org/2.1/collection/docgen&_resource=http%3A//qudt.org/schema/qudt/Quantity 

Not sure what is going on here?

**Comment by steveraysteveray** [comment]
Hi, thanks for mentioning this. We'll have to go back and take a look at the code that generated those pages (which was a while ago). It's true that our classes are not resolvable the way all of our vocabulary instances are. However, until we fix this, I encourage you to go back to the homepage and click on the "QUDT Resources" section, either choosing the ["QUDT Catalog Release 2.1" link](http://www.qudt.org/2.1/catalog/qudt-catalog.html) or the ["QUDT EDG environment"](http://www.qudt.org/edg/tbl) link, from which you can find all the classes.

**Comment by DrMaggie** [comment]
Hi @steveraysteveray , thank you so much for responding so quickly to my question! I'll follow your kind advise to look for the class descriptions! BTW, I arrived at the QUDT pages while following up on references given during a discussion earlier today in the RDA I-ADOPT working group - which just shows that also older web content is still considered relevant today :>)

**Comment by steveraysteveray** [comment]
That's good to hear. Don't hesitate to ask if you have further questions.

**Comment by dr-shorthair** [comment]
> It's true that our classes are not resolvable the way all of our vocabulary instances are.

Indeed. And until they are, this will remain a barrier to adoption in the broader semantics/linked data community ... #107 has been sitting their a bit unloved for almost a year. Would it be possible to bump up the priority?

**Comment by steveraysteveray** [comment]
Just thought I'd mention that all the classes and properties are now resolvable!

**Comment by dr-shorthair** [comment]
They do not resolve for me :-( 
I get a redirect to things like 

http://www.qudt.org/pages/swp?_base=http%3A//rdfex.org/withImports%3Furi%3Dhttp%3A//qudt.org/2.1/collection/docgen&_resource=http%3A//qudt.org/schema/qudt/Quantity 

and a 404

**Comment by steveraysteveray** [comment]
I stand by my statement: The classes and properties do resolve. However, the overview diagrams in question don't just link to the URIs of the classes or properties - they link to the SWP calls that you listed above. I have examined the code that generates those diagrams, and it is not for the faint of heart! Templated functions with parameters generated by surrounding contexts, etc. They have so far eluded my attempts to have them replaced by a simple link to something like [http://qudt.org/schema/qudt/Quantity](http://qudt.org/schema/qudt/Quantity). 

Give me some credit - at least I got the classes and properties to resolve!

**Comment by dr-shorthair** [comment]
Yes - the URIs resolve. That is definitely the most important thing and a big step forward. 
I feel more confident pointing Linked Data folk at QUDT now. Well done. :-) 

The links I tried were indeed from the diagram. They look like links, but don't act like them at present :-(

**Comment by steveraysteveray** [comment]
OK, at last, the diagrams found in the [Overview page](http://www.qudt.org/pages/QUDToverviewPage.html) are now working, so that you can click on any of the classes in the diagrams to navigate to a description page.

**Comment by dr-shorthair** [comment]
Onya Steve.

**Comment by steveraysteveray** [comment]
Had to look up onya, but thanks! 😀
