### ISSUE TITLE
Illegal character found in description for unit barn

### ISSUE THREAD

**Issue by stuchalk** [qudt/qudt-public-repo#371]
On export of the [units vocabulary](https://github.com/qudt/qudt-public-repo/blob/master/vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl) to RDF/XML and opening in OxygenXML an 'illegal character' was identified in the `dcterms:description` entry for the unit 'barn'.  The character precedes the '28' inside the curly braces.

**Comment by jhodgesatmb** [comment]
Stuart,

Why don’t you fix the error and submit a pull request?

Jack Hodges, Ph.D.
Arbor Studios

**Comment by stuchalk** [comment]
PR merged so issue fixed...

**Comment by stuchalk** [comment]
Jack

Thanks for the prod.  Its done and approved by Steve ;)

Stuart

On Mar 27, 2021, at 7:02 PM, jhodgesatmb ***@***.******@***.***>> wrote:


Stuart,

Why don’t you fix the error and submit a pull request?

Jack Hodges, Ph.D.
Arbor Studios

**Comment by jhodgesatmb** [comment]
Stuart,

I went to review/approve your PR yesterday and found that Steve had already done so. Excellent! Thank you.

Jack Hodges, Ph.D.
Arbor Studios
