### ISSUE TITLE
quantitykind:MassFlowRate typo

### ISSUE THREAD

**Issue by VladimirAlexiev** [qudt/qudt-public-repo#382]
quantitykind:MassFlowRate seems to have some stray "curly brackets vs quotes" in dcterms:description:

`"\"Mass Flow Rate} is a measure of Mass flux. The common symbol is \\(\\dot{m\"\\)`

**Comment by steveraysteveray** [comment]
Fixed to display 
![image](https://user-images.githubusercontent.com/1130189/115482857-76b3dd00-a204-11eb-91ac-106175e6445f.png)

This is fixed in branch srr-minor-fixes, which will be merged soon.

It will show up on our web pages in the next publishing cycle.

**Comment by VladimirAlexiev** [comment]
Yiu still have a stray curly in `Mass Flow Rate}`

**Comment by steveraysteveray** [comment]
Actually, I think it was fixed in the subsequent commit. Take a look at the current master branch.
