### ISSUE TITLE
Make qudt:Concept sub-class-of skos:Concept

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#39]
QUDT individuals can be reasonably understood to behave as a special kind of 'concept' in the sense designed in SKOS. Conceived this way, sets of QUDT individuals could be managed and published through standard vocabulary services. 

All that is needed is to add the axiom
```
qudt:Concept rdfs:subClassOf skos:Concept .
```

**Comment by nicholascar** [comment]
Could QUDT consider using `skos:Concept` directly instead of subclassing?

**Comment by steveraysteveray** [comment]
As I understand it, there are many entailments for a skos:Concept, which may or may not be appropriate for QUDT individuals. I need to study up more on skos.

**Comment by dr-shorthair** [comment]
Not really. And none that would get in the way, that I have encountered.

**Comment by nicholascar** [comment]
Agreed: no problematic entailment for skos:Concept that I can think of, indeed there are hardly any entailments at all. There are no mandatory properties, whole/part relations that place Concepts in relation to other containers, etc.

Concepts really just indicate the thing is generically an abstract *concept* and that certain annotation properties - the SKOS labels - can be used and other object properties could be used to relate it to other concepts in a hierarchy.

**Comment by nicholascar** [comment]
See PR #57
