### ISSUE TITLE
description rendered in a mangled way

### ISSUE THREAD

**Issue by VladimirAlexiev** [qudt/qudt-public-repo#390]
http://qudt.org/vocab/unit/W: 

Description is momentarily rendered as text, but then is converted to an image using math font and becomes nearly unreadable:
![image](https://user-images.githubusercontent.com/536250/115705273-05476c00-a375-11eb-977b-fe7cb5783106.png)

In contrast, latexDefinition is rendered in a useful and readable way:
![image](https://user-images.githubusercontent.com/536250/115705424-30ca5680-a375-11eb-981b-244a824fec40.png)

I looked at the source and the problem is in the data:

`dct:description "\\(...\\)"^^<http://qudt.org/schema/qudt/LatexString>`

Need to check all dct:description that:
- have the indicated datatype, OR
- include latex math delimiter `\\(` , and maybe also `$$` ?

**Comment by jhodgesatmb** [comment]
There is nothing ‘latex’y about LatexString and it shouldn’t be used in a dct:description anyway. Probably just a scripting oversight.

Jack Hodges, Ph.D.
Arbor Studios

**Comment by steveraysteveray** [comment]
@VladimirAlexiev, thanks. We're grinding through all these descriptions (again) as we speak. A couple of PRs will be coming up shortly.
