### ISSUE TITLE
qudt:conversionMultiplier

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [qudt/qudt-public-repo#405]
Hi 
I want to add the following units: MilliMOL-PER-M2-SEC (ucumCode "mmol.m-2.s-1")
How can I calculate the conversionMultiplier for the units above?

**Comment by dr-shorthair** [comment]
It is the multiplier required to convert quantities in this uom to the corresponding SI unit. 
So in this case it is 0.001 since 

1 MilliMOL-PER-M2-SEC = 0.001 MOL-PER-M2-SEC

**Comment by kitchenprinzessin3880** [comment]
Thanks Simon!  I will send a pull request now ;)
