### ISSUE TITLE
Add quantitykind PAR (PPF, PPFD)

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [qudt/qudt-public-repo#409]
Add a quantitykind for PAR, such as described here[1], and have the new unit point to it? Guidance for quantitykind contributions is found here [2].

Related Links:
[1] https://www.gigahertz-optik.com/en-us/service-and-support/knowledge-base/measurement-of-par/
[2] https://github.com/qudt/qudt-public-repo/wiki/QuantityKind-Vocabulary-Submission-Guidelines

**Comment by steveraysteveray** [comment]
Great! Thanks.

**Comment by steveraysteveray** [comment]
I'll just leave your first branch un-merged, and you can add the quantity kinds there in that PR.

**Comment by kitchenprinzessin3880** [comment]
@steveraysteveray can you please merge it? we need to populate the units in our editorial system today to create metadata records..i will update the unit file next week once i create the quantitykind.

**Comment by steveraysteveray** [comment]
Done.
