### ISSUE TITLE
False offset value in Degree Fahrenheit/DEG_F

### ISSUE THREAD

**Issue by LeebPhil** [qudt/qudt-public-repo#413]
Hey guys, 

you set the offset value of DEG_F to 459.669607 but it should be 255.37037037037037037E0  
  
Just had the problem when converting from Celsius to Fahrenheit when calculating:  
((celsius.value * celsius.multiplier + celsius.offset) - fahrenheit.offset) / fahrenheit.multiplier  
  
With an fahrenheit-offset of 459.669607 this would lead to almost -300°F and not 68°F when celsius.value is 20°C

**Comment by steveraysteveray** [comment]
@LeebPhil, please see our wiki [here](https://github.com/qudt/qudt-public-repo/wiki/Support-for-measures-of-absolute-values-and-for-intervals-(differences)#converting-units-on-linear-scales) for our use of conversion offsets and multipliers. The formula used depends on the definitions of those terms. Your formula is not compatible with our definitions.

Not a show-stopper. You just need to convert the conversion!

**Comment by LeebPhil** [comment]
@steveraysteveray thank you for the hint. Then the calculation has to be adjusted.

**Comment by Rdataflow** [comment]
@steveraysteveray thank you for this clarification on the *native scale* offset, which IIUC uncovers yet another issue:
MilliDEG_C should thus have an offset of 273150 ~rather than 273.15~
