### ISSUE TITLE
Show item URI in pop-up

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#418]
The pop-ups that you get to when you select a resource in any of the vocabularies, such as http://www.qudt.org/doc/DOC_VOCAB-CONSTANTS.html and http://www.qudt.org/doc/DOC_VOCAB-UNITS.html, do not show the URI. Yes it is behind one of the links, but better if it is shown up front, without asking the user to go hunting IMAO

**Comment by dr-shorthair** [comment]
Follow-up to #416

**Comment by steveraysteveray** [comment]
@dr-shorthair, I was revisiting this, and I clicked on one of our units and got the following:
![image](https://user-images.githubusercontent.com/1130189/125524302-b460ae3c-8090-4f4c-be60-86b39cd4e717.png)

The title of the popup is the URI, so I'm wondering whether you are asking that it should be an active link, or did you just not see that because it is so big? :)

**Comment by dr-shorthair** [comment]
The title is strictly not actually a URI, it is a cURI. 
This means that you can't copy-paste it into another application (e.g. an editor). 
I guess that is what I'm looking for.

**Comment by steveraysteveray** [comment]
OK, let me think about this for an elegant solution.

**Comment by dr-shorthair** [comment]
In vocabularies that I am publishing these days I often use the pattern below to hold the full URI as a string in its own property. That way you can display it as a suitably labelled annotation in a form that can be easily copied - e.g. 

```turtle
<http://qudt.org/vocab/unit/BTU_IT-IN-PER-FT2-SEC-DEG_F>
  rdf:type <http://qudt.org/schema/qudt/DerivedUnit> ;
  rdf:type <http://qudt.org/schema/qudt/Unit> ;
  dcterms:identifier "http://qudt.org/vocab/unit/BTU_IT-IN-PER-FT2-SEC-DEG_F"^^xsd:anyURI ; 
  <http://purl.org/dc/terms/description> "\\(BTU_{IT}\\), Inch per Square Foot Second Degree Fahrenheit, is an Imperial unit for 'Thermal Conductivity' expressed as \\(Btu_{it}-in/(ft^{2}-s-degF)\\)."^^<http://qudt.org/schema/qudt/LatexString> ;
  <http://qudt.org/schema/qudt/conversionMultiplier> 519.220399911 ;
  <http://qudt.org/schema/qudt/expression> "\\(Btu(it)-in-per-s-ft2-degF\\)"^^<http://qudt.org/schema/qudt/LatexString> ;
  <http://qudt.org/schema/qudt/hasDimensionVector> <http://qudt.org/vocab/dimensionvector/A0E0L1I0M1H-1T-3D0> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/ThermalConductivity> ;
  <http://qudt.org/schema/qudt/iec61360Code> "0112/2///62720#UAA118" ;
  <http://qudt.org/schema/qudt/informativeReference> "http://www.translatorscafe.com/cafe/EN/units-converter/thermal-conductivity/c/"^^xsd:anyURI ;
  <http://qudt.org/schema/qudt/plainTextDescription> "British thermal unit (international table) inch per second Square foot degree Fahrenheit is the unit of the thermal conductivity according to the Imperial system of units." ;
  <http://qudt.org/schema/qudt/ucumCode> "[Btu_IT].[in_i].[ft_i]-2.s-1.[degF]-1"^^<http://qudt.org/schema/qudt/UCUMcs> ;
  <http://qudt.org/schema/qudt/ucumCode> "[Btu_IT].[in_i]/([ft_i]2.s.[degF])"^^<http://qudt.org/schema/qudt/UCUMcs> ;
  <http://qudt.org/schema/qudt/uneceCommonCode> "J42" ;
  <http://qudt.org/schema/qudt/unitOfSystem> <http://qudt.org/vocab/sou/IMPERIAL> ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "BTU (IT) Inch per Square Foot Second Degree Fahrenheit"@en ;
  owl:sameAs <http://qudt.org/vocab/unit/BTU_IT-IN-PER-SEC-FT2-DEG_F> ;
.
```

**Comment by steveraysteveray** [comment]
Rather than add yet another property, I tweaked the page generation code to display the URI to look like this:

![image](https://user-images.githubusercontent.com/1130189/126240759-5dd528c9-2ef9-458b-a820-e9407545d212.png)

Next time I republish all the pages, this should work for all vocabulary instances.

**Comment by dr-shorthair** [comment]
Thx @steveraysteveray
