### ISSUE TITLE
QUDT website on HTTPS has broken visuals

### ISSUE THREAD

**Issue by Ostrzyciel** [qudt/qudt-public-repo#424]
When opening `https://www.qudt.org/` in a modern browser, the content of the page appears broken, with CSS and imagery not loading. This is only apparent when using the HTTPS protocol, everything works fine with HTTP.
![www qudt org_](https://user-images.githubusercontent.com/56843159/127275097-5f6b251f-dd72-445d-a10c-8bb75b43e45c.png)

According to Chrome's developer console, this is due to bad handling of mixed content, see [this MDN article for a full explanation](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content). It's also worth mentioning that modern browsers and Google Search will default to HTTPS when available, so this is how the website appears to most users.

**Comment by steveraysteveray** [comment]
Thanks for raising this issue. It's one we are aware of, but not easily fixed. This is because we generate all our pages using external libraries for rendering parts such as the Latex equations. Some of those external libraries themselves are not available via https, which therefore makes our own pages only http-ready.

We definitely plan to tackle our whole page-rendering approach at some point, but until then we're forced to live with http.

**Comment by bhpayne** [comment]
I'm getting a "Tomcat welcome page" regardless of whether I use `http` or `https` in Chrome. In Firefox I get the "Tomcat welcome page" using `https` and I get the correctly rendered page when using `http`.

**Comment by steveraysteveray** [comment]
Hmm. I just tested this with Chrome, both incognito and regular, and http://qudt.org seems to work for me...

**Comment by steveraysteveray** [comment]
@bhpayne, just wanted to check with you if things are working OK now. I did migrate our entire site to a new AWS instance last week, so there were some times where things were being tweaked.   (Also, we hope to solve the https problem soon!)

**Comment by NicolasCARPi** [comment]
Hello,

The https version of your website is showing the default tomcat page. Trying to access the schemas through https gives 404 errors. You already have a working TLS config with a valid certificate, so please try and fix your server configuration so we can use https like the rest of the web ;)

Best,
~Nico

**Comment by steveraysteveray** [comment]
Agreed.

**Comment by steveraysteveray** [comment]
This has been fixed as of Release 2.1.18
