### ISSUE TITLE
Remove trailing spaces from 4 labels

### ISSUE THREAD

**Issue by nicholascar** [qudt/qudt-public-repo#437]
A few unit labels contain trailing spaces:

"Dyne Centimeter "@en-us
"Dyne Centimetre "@en
"Kilometer "@en-us
"Kilometre "@en

Discovered by the SPARQL query on the QUDT SPARQL endpoint:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?s ?lbl
WHERE {
  ?s rdfs:label ?lbl .
  
  FILTER REGEX(?lbl, " $")
}
```

**Comment by steveraysteveray** [comment]
Any chance you could submit a pull request?

**Comment by nicholascar** [comment]
will do!
