### ISSUE TITLE
Issues with unit:V and quantitykind:Voltage

### ISSUE THREAD

**Issue by drth80** [qudt/qudt-public-repo#441]
Hi,

in a project, I am using QUDT to guide users in selecting valid combinations of quantitykinds and units to represent properties of e.g. products. I really love the value and flexibility that QUDT provides here!

Today, we stumbled over a situation that I would consider an inconsistency:
- The user selects quantityKind:Voltage to be measured.
- We retrieve all applicable units, which for instance include kV, mV etc - but not V
- Investigation shows that V is listed only as an applicable unit for quantitykind:EnergyPerElectricCharge, which is stated to be owl:sameAs quantitykind:Voltage .

While we could surely also identify V as a relevant unit, it's surprising to me that V and all its "trivially derived" units such as mV, kV, etc are associated with different quantity kinds. As we're unluckily bound to use Neptune, we would either have to write more complex queries involving property paths, or have a pre-materialization step for QUDT. So I was wondering if the QUDT team plans to change something here?

Additional observations:
- While unit:V is marked to be a qudt:DerivedUnit, the other units that are what I called "trivially derived" from it in natural language (kV, mV, ...) are only classified as qudt:Unit. This is counterintuitive.
- The unit browser at http://www.qudt.org/edg/tbl/qudt_units.editor does not find volts either, which initially even lead me to think QUDT misses it.

**Comment by steveraysteveray** [comment]
Thanks, that's gratifying to hear. I have fixed your reported error and have:
- Regenerated our [web pages](http://qudt.org/) and [catalog](http://www.qudt.org/2.1/catalog/qudt-catalog.html)
- Repopulated the [EDG server](http://www.qudt.org/edg/tbl)
- Repopulated our [SPARQL endpoint](http://www.qudt.org/fuseki)

Please let me know if you see any issues.

**Comment by drth80** [comment]
Excellent, thank you so much. We will check and get back if we find anything on top.
