### ISSUE TITLE
New Unit: MYA

### ISSUE THREAD

**Issue by nicholascar** [qudt/qudt-public-repo#452]
I would like to register MYA - Millions of Years Ago - which is the main temporal unit used in geology and, in particular, the International Stratigraphic Commission.

QUDT already contains MegaYR (aka MA, "1,000,000-fold of the derived unit year") but MYA is different: it's MegaYR counting backwards from "present", with "present" being modern human time (centuries don't matter to MYA).

Yes MYA has both an increment, 1x10^6 YR, and a starting point "now", but I a unit that combines an increment + starting point has precedence in QUDT with Kelvin and perhaps others.

I propose the following formal definition:

```turtle
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix qudt: <http://qudt.org/schema/qudt/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix unit: <http://qudt.org/vocab/unit/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://qudt.org/vocab/unit/MYA>
    a qudt:DerivedUnit , qudt:Unit ;
    qudt:conversionMultiplier -31557600000000.0 ;
    qudt:hasDimensionVector <http://qudt.org/vocab/dimensionvector/A0E0L0I0M0H0T1D0> ;
    qudt:hasQuantityKind <http://qudt.org/vocab/quantitykind/Time> ;
    qudt:informativeReference "https://simple.wikipedia.org/wiki/Mya_(unit)"^^xsd:anyURI ;
    qudt:isScalingOf unit:YR ;
    qudt:plainTextDescription "1,000,000-fold of the derived unit year, directed to the past, 
                              from the present. the present is the modern human era which is 
                              of the order of thousands of years and of insignificant length with 
                              respect to millions of years so it appears as a time instant." ;
    qudt:prefix <http://qudt.org/2.1/vocab/prefix/Mega> ;
    qudt:symbol "MYA" ;
    qudt:ucumCode "Ma"^^<http://qudt.org/schema/qudt/UCUMcs> ;
    rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
    rdfs:label "Million of Years Ago"@en ;
    skos:altLabel "MYA" ;
.
```
This definition is similar to MegaYR but the comversion multiplier is negative, is that sensible? Should I instead derive from MegaYR?

**Comment by steveraysteveray** [comment]
You raise an interesting point that we talk about in the wiki [here](https://github.com/qudt/qudt-public-repo/wiki/Support-for-measures-of-absolute-values-and-for-intervals-(differences)). Namely, MYA is an interval measure and really belongs in the context of a qudt:Quantity rather than a unit. The qudt:Quantity class has a property qudt:isDeltaQuantity. I think the right pattern is to instantiate your own qudt:Quantity, with the delta flag set, and use unit:MegaYR. It's true that this doesn't tell you that the delta is from the present time, just that it is a delta of megayears...  The negative sign on your quantity would tell you that you are going into the past, though.

**Comment by nicholascar** [comment]
On reflection, I think an easier way of going about this is to use an MYA Temporal Reference System, following OWL TIME's [5.2 Use of temporal reference systems](https://www.w3.org/TR/owl-time/#different-TRS).

If I want to then say that something happened 66 MYA, I would say:

```turtle
ex:CometStrike
    a prov:Activity ;
    time:hasTime [
        a time:Instant ;
        time:inTimePosition [
            time:numericPosition 66 ;
            time:hasTRS <http://resource.geosciml.org/classifier/cgi/geologicage/ma> ;
        ] ;
    ] ;
```

I still use MegaYR for certain forms of counting, like durations: 

```turtle
@prefix gts: <http://resource.geosciml.org/ontology/timescale/gts#> .
@prefix time: <http://www.w3.org/2006/time#> .
@prefix unit: <http://qudt.org/vocab/unit/> .

isc:BaseJurassicTime
    a time:TimePosition ;
    time:hasTRS <http://resource.geosciml.org/classifier/cgi/geologicage/ma> ;
    time:numericPosition 201.3 ;
    gts:positionalUncertainty [
        a time:Duration ;
	time:numericDuration 0.2 ;
	time:unitType unit:MegaYR ;
    ] ;
.
```

So the missing thing is the Temporal Reference System (TRS) that defines what "Millions of Year Ago" means.

The Semantic Web version of the Geologic timescale (http://resource.geosciml.org/vocabulary/timescale/gts2020) uses `<http://resource.geosciml.org/classifier/cgi/geologicage/ma>` for Millions of Years Ago but it defines it itself and never enabled the URI to resolve. So I'll get that resolution working now and then this issue is solved.

```turtle
<http://resource.geosciml.org/classifier/cgi/geologicage/ma> 
    a time:TRS ;
    rdfs:seeAlso 
        <https://doi.org/10.1351%2FPAC-REC-09-01-22> , 
        <https://en.wikipedia.org/wiki/Year#SI_prefix_multipliers> ;
    skos:definition "Temporal position expressed numerically scaled in millions of years increasing 
                    backwards from the present"@en ;
    skos:prefLabel "Millions of years ago"@en ;
    owl:sameAs "http://www.opengis.net/def/crs/OGC/0/ChronometricGeologicTime"^^xsd:anyURI .
```
Nothing for QUDT to do here!
