### ISSUE TITLE
best practice for using versioned iris in relation from unit to prefix

### ISSUE THREAD

**Issue by fkleedorfer** [qudt/qudt-public-repo#454]
Some Units have prefixes, e.g.

```
<http://qudt.org/vocab/unit/KiloA> <http://qudt.org/schema/qudt/prefix> <http://qudt.org/2.1/vocab/prefix/Kilo> .
```

However, their IRIs are 'versioned', i.e., they contain the ontology version number. These IRIs are nowhere to be found in the prefixes file accessible at https://qudt.org/2.1/vocab/prefix. 

In contrast, the relationship between `Unit` and `QuantityKind` is not 'versioned' in this way. 

For my use case, I download the ttl files I need (unit, quantitykind, prefix) and put the data into a local rdf store. When I try to join `Unit` and `Prefix` the attempt fails (obviously, once you know). My quick fix is to change the `qudt:prefix` uris that the unit entitys point to, but that's a hassle as I have to do this with every update. What's the best practice here?

**Comment by steveraysteveray** [comment]
Florian,
Thanks so much for catching this! We hadn't really explicitly used the prefix individuals much, so the reference from the units slipped by unnoticed. It is definitely an error - luckily easily fixed with a global replace to remove the version number. Please stay tuned for an update.
