### ISSUE TITLE
sparql to convert  from μmol/kg, mol/kg TO mmol/m3

### ISSUE THREAD

**Issue by alko-k** [qudt/qudt-public-repo#514]
Hi @steveraysteveray  and all,

I have a wish to make and I will show what I would like to happen with example queries attached here:
The attached query gets all the conversions FROM mol/m3, μmol/lt, picomole/lt, mmol/lt, mol/lt, picomoles/m3, femtomoles/lt and mmol/m3  TO  mmoles/m3
[MOLPVOLconversions.txt](https://github.com/qudt/qudt-public-repo/files/9020898/MOLPVOLconversions.txt)

Is it possible to add the conversion from mol/kg mmol/kg etc to mmoles/m3?
Currently such a query returns nothing. We only want the equation type assuming that the density would be given.

Thanks
Alexandra
.

**Comment by steveraysteveray** [comment]
Yes, doing the conversions from mol/<mass> to mol/<volume> would be possible, with the key missing ingredient being the source of the density (or molecular weight). If there were a SPARQL endpoint providing such a thing, then you could embed another SERVICE call for a specific material to retrieve its density, and include that in your conversion calculation.

We discussed this at the recent Units Summit based on your prerecorded presentation, and there was agreement that such a federated approach would be preferable to having any one source provide all the kinds of data needed. During the discussion, I challenged NIST to provide such a SPARQL service.

Am I answering your question, or are we talking past each other?

**Comment by alko-k** [comment]
Hi Steve, the conversions Iam suggesting being offered by qudt, are what UCUM is offering when assuming that the molecular weight is known and given as a parameter e.g. https://ucum.nlm.nih.gov/ucum-service/v1/ucumtransform/1/from/mg/dL/to/mmol/L/MOLWEIGHT/180.156

**Comment by jhodgesatmb** [comment]
I I talked with the QUDT board some time ago about seeing if there is an online version of the CRC handbook. Sadly it is a subscription service.

Jack Hodges, Ph.D.
Arbor Studios

**Comment by dr-shorthair** [comment]
Molecular mass is available from ChEBI. 

For example https://www.ebi.ac.uk/ols/api/ontologies/chebi/terms?iri=http://purl.obolibrary.org/obo/CHEBI_38892
HTTP header Accept = application/json gets something machine processable from OLS. 
Within the `annotation` block see 
```
                    "mass": [
                        "237.24990"
                    ],
                    "monoisotopicmass": [
                        "238.00229"
                    ],
```

**Comment by jhodgesatmb** [comment]
It would not make sense for QUDT to publish a SPARQL query as a general solution unless the query can be applied generally (and without a service fee). As an example only it would, I am sure, be fine.

Jack Hodges, Ph.D.
Arbor Studios

**Comment by alko-k** [comment]
@steveraysteveray thank you for the query, it looks brilliant. I use the  FILTER(!langMatches(lang(?otherUnitLabel ), "en-us")) to exclude the en-us language.

@dr-shorthair thank you for the ebi API suggestion. I can write python snippet in jupyter to call the ebi service, get the molecular weight and then run the sparql query to get the unit conversions.  @jhodgesatmb  I will post when I do. 
Thank you all for your help, it is very much appreciated
