### ISSUE TITLE
Wrong multiplier for <http://qudt.org/vocab/unit/FemtoMOL-PER-KiloGM>

### ISSUE THREAD

**Issue by alko-k** [qudt/qudt-public-repo#538]
Hi again Steve,

I think that the multiplier for <http://qudt.org/vocab/unit/FemtoMOL-PER-KiloGM> should be corrected as it currently is 0.15. 
The multiplier for <http://qudt.org/vocab/unit/PicoMOL-PER-KiloGM> is 0.000000000001

Thank you 
Alexandra

**Comment by steveraysteveray** [comment]
Thanks for this! Indeed, at some point in the past, some of these very small factors that had been expressed as 10**-15 (for example) got misinterpreted and ended up as 0.15 instead. I just found another one with 0.18. I'll fix the ones I can find. Let me know if you find others after my next fix.

**Comment by alko-k** [comment]
Hi @steveraysteveray  thank you for taking care of this :-)
Is the correction in production? I cannot see it yet.

**Comment by steveraysteveray** [comment]
The updates have been merged to the master branch in GitHub. Just now, I refreshed the datasets for the Fuseki endpoint. I don't plan to update our qudt.org web pages until September, though.

**Comment by alko-k** [comment]
Thanks @steveraysteveray . Iam only interested in the sparql endpoint for now :-)
Can you please check the following?
<http://qudt.org/vocab/unit/PicoMOL-PER-KiloGM> conversion multiplier is a decimal. 
But <http://qudt.org/vocab/unit/FemtoMOL-PER-KiloGM> and Femtograms per litre conversion multipliers are of type numeric union and need to be changed to decimal.

Thank you
Alexandra

**Comment by steveraysteveray** [comment]
My mistake. Should be fixed in #544. Once it is approved I'll upload to the endpoint.
