### ISSUE TITLE
Some xsd:decimal representations are too long for some triple stores

### ISSUE THREAD

**Issue by mgberg** [qudt/qudt-public-repo#542]
One of the triple stores we're using encodes literals of certain XSD datatypes to enable fast lookup, conversion, and range and order queries on values of those types. Unfortunately, conversion multipliers for a few of the Planck units are so long that they fall out of their spec for accepted values for `xsd:decimal`, and therefore the unit graph cannot be loaded into this triple store without modification.

There are five units which fall in this category: `unit:PlanckArea`, `unit:PlanckCurrentDensity`, `unit:PlanckDensity`, `unit:PlanckPressure`, `unit:PlanckVolume`.

One possible solution is to convert the conversion multiplier for at least these units from `xsd:decimal` to `xsd:double`. However, I'm not sure what the current ruling is on datatypes used for conversion multipliers/offsets. I know that at one point it was decided to make everything `xsd:decimal`s to reduce issues regarding floating-point arithmetic, but it seems that decision was reversed a few months ago.

**Comment by steveraysteveray** [comment]
While we clear this up, I have declared the multipliers for the units you mentioned as xsd:double explicitly. Slipped this fix into #544.

**Comment by mgberg** [comment]
Great! I have confirmed that loading the file as it is in #544 works as intended.

**Comment by mgberg** [comment]
Great! I have confirmed that loading the file as it is in https://github.com/qudt/qudt-public-repo/pull/544 works as intended.

**Comment by jmkeil** [comment]
> One of the triple stores we're using encodes literals of certain XSD datatypes to enable fast lookup, conversion, and range and order queries on values of those types. Unfortunately, conversion multipliers for a few of the Planck units are so long that they fall out of their spec for accepted values for `xsd:decimal`, and therefore the unit graph cannot be loaded into this triple store without modification.

@mgberg Which triplestore implementation causes the problem? [xsd:decimal specifications](https://www.w3.org/TR/xmlschema11-2/#decimal) (including [ minimally conformance requirements](https://www.w3.org/TR/xmlschema11-2/#partial-implementation)) do not limit the length of values. It must be the triplestore, not the values, that doesn't meet the specifications.

**Comment by jmkeil** [comment]
@mgberg Of course, a reasonable design decission. I am curious: Which triplestore software is that? Is the limit configurable or hard coded?

**Comment by mgberg** [comment]
AllegroGraph; their datatype documentation is [here](https://franz.com/agraph/support/documentation/current/datatypes.html).
