### ISSUE TITLE
Wrong conversion multipliers for KiloBYTE, MegaBYTE and GigaBYTE

### ISSUE THREAD

**Issue by paroga** [qudt/qudt-public-repo#586]
At the moment `KibiBYTE` and `KiloBYTE` are both defined as 1024 byte.

While `KiloBYTE` references the `uneceCommonCode` `2P` (1000 bytes) `KibiBYTE` references `E64` (1024 bytes).

Other data sources like [wikidata](https://www.wikidata.org/wiki/Q79726) expect `KiloBYTE` to be 1000 bytes already. I don't think that's a normative reference, but IMO it shows that other people had similar expectations.

As already stated in #582, I think having both `KiloBYTE` and `KibiBYTE` with the same conversion multipliers is just wrong. I'm aware of the historical background, but keeping the same "mistakes" does not feel right to me.

The same issue applies to `MegaBYTE` and `GigaBYTE` too.

**Comment by steveraysteveray** [comment]
Finished up in PR #602
