### ISSUE TITLE
Is it intentional that the RDF Subject of QUDT's `owl:Ontology` triple is missing a trailing slash (and so is *different* to the QUDT namespace IRI)?

### ISSUE THREAD

**Issue by pmcb55** [qudt/qudt-public-repo#589]
It's explicitly stated in the QUDT 'Abstract' (here: https://www.qudt.org/doc/DOC_SCHEMA-QUDT.html) that the namespace for QUDT is `http://qudt.org/schema/qudt/` (**_with_** a trailing slash).

However, the actual Turtle for QUDT (visible by simply browsing-to that namespace IRI) doesn't define any triples for this namespace IRI. Instead it defines the following triples for that namespace IRI **_without_** the slash, i.e.:
```
<http://qudt.org/schema/qudt> a owl:Ontology ;
  <http://www.linkedmodel.org/schema/vaem#hasGraphMetadata> <http://www.linkedmodel.org/schema/vaem#GMD_QUDT-SCHEMA> ;
  rdfs:isDefinedBy <http://qudt.org/2.1/schema/qudt> ;
  rdfs:label "QUDT Schema - Version 2.1.20" ;
  owl:imports <http://www.linkedmodel.org/schema/dtype> ;
  owl:imports <http://www.linkedmodel.org/schema/vaem> ;
  owl:imports <http://www.w3.org/2004/02/skos/core> ;
  owl:versionIRI <http://qudt.org/2.1/schema/qudt> .
```

Is this an oversight, or in any way intentional?

This is very important for machines trying to 'follow-their-nose' from a vocab's namespace IRI to specific triples 'about' that vocab (such as the `rds:label` or `owl:versionIRI` information in the triples shown above). I think this is critically important, as a vocab's namespace IRI is the one and only *standardized* entrypoint to any vocabulary (that I'm aware of). Yet, if the IRI's are different (as they are here with QUDT), then how can any machine easily find that vocab label or version info given it starts with just the namespace IRI of a vocab...?

Also Note: the comment on the first line when dereferencing the QUDT namespace IRI:
```
# baseURI: http://qudt.org/schema/qudt
```
This seems like a (possibly related) 'bug', as I'd always expect BaseURIs to always have a trialing hash or slash, as otherwise relative IRIs (e.g., `<AngleUnit>`) become amibiguous (i.e., should the absolute IRI actually be `http://qudt.org/schema/qudt/AngleUnit` or `http://qudt.org/schema/qudt#AngleUnit` (I think most RDF parsers will assume the former, but 'assuming' anything ain't ever good, and being explicit in the relative IRI (e.g., `</AngleUnit>` or `<#AngleUnit>`) kinda defeats the whole purpose of having less noise in relative IRIs!)).

Similarly, all the terms in QUDT have `rdfs:isDefinedBy` triples (which I think is great!), but they all refer to 'incorrect' IRIs (i.e., the QUDT namespace IRI *without* a trailing slash). So prehaps this really is intentional (as there are arguments to justify having explicitly _different_ IRIs for an 'ontology' and it's 'namespace')) - but if so, I'd really appreciate understanding QUDT's intent behind that, and whether the ability to automatically 'follow-ones-nose' from the vocab namespace IRI to the triples describing that vocab is not really deemed that important.

(Also, just for reference, other common, popular vocabs that provide `rdfs:isDefinedBy` triples for their vocab terms (e.g., such as OWL, XSD,  SHACL, ShEx, LDP, FOAF, DCTERMS, DPV, ODRL, PROV-O, BIBO, DOAP, OLO, SIOC, SOSA, etc.) **_all_** provide IRI values that **_exactly_** match their vocab namespace IRI.)

Notable exceptions I notice though are [vCard](http://www.w3.org/2006/vcard/ns#), ADMS, DataCube, SKOS, which all do exactly the same as QUDT, i.e., their `rdfs:isDefinedBy` triples point at the their namespace IRI **_without_** the trailing hash or slash.

And then we have [DCAT](http://www.w3.org/ns/dcat#), whose `rdfs:isDefinedBy` values point at the HTML specification (and not RDF at all), and [SDMX-Dimension](http://purl.org/linked-data/sdmx/2009/dimension#) that point to a PDF!

So it seems the majority of vocabs out there point to *exactly* their vocab's namespace IRI - so I'm curious to know if QUDT considered this queston at all, and consciously came to the conclusion we see today, or would it be worth reconsidering and discussing (i.e., should the subject of `<> a owl:Ontology` triples really be *different* to the vocab's namespace IRI, should it match *exactly*, or does this community think it just doesn't matter(!)...?).

**Comment by steveraysteveray** [comment]
We believe we have been consistent in our URIs and prefixes, as follows:
1. The base URIs in QUDT are all without any trailing / or #.
2. The prefix definitions for QUDT graphs all use /. One reason for this is because the vocabularies are rather large.
3. The rdfs:isDefinedBy triples refer to the base URI (which is the persistent entity).

These were intentional decisions. We could discuss of course, but changing the baseURI at this point would break FAIR principles (since they would change) and likely many applications already built.
