### ISSUE TITLE
Incorrect use of m (~meter) in Kelvin-per-minute

### ISSUE THREAD

**Issue by jecop** [qudt/qudt-public-repo#590]
As fas as I can see,  m stands for meter and min for minute, but in Kelvin-per-minute https://qudt.org/vocab/unit/K-PER-MIN.html  the expression shown is K/m, which I assume is Kelvin per meter
Kelvin-per-metre does not have an expression

**Comment by steveraysteveray** [comment]
Good catch, thanks! Would you mind submitting a pull request? If that's too much of a lift in your environment, let me know and I'll try to remember to include it in my next update.

**Comment by jecop** [comment]
I don't have a dev environment set up at the moment. I'll try do that, but I'm not working with Git very often so it will take some time

**Comment by steveraysteveray** [comment]
Don't worry about it. I'll take care of it.
