### ISSUE TITLE
Potential issue involving qudt:SymbolAndExpressionDisjointPropertiesConstraint

### ISSUE THREAD

**Issue by mgberg** [qudt/qudt-public-repo#605]
`qudt:SymbolAndExpressionDisjointPropertiesConstraint` is a SHACL SPARQL constraint in the SHACL Supplements graph that checks that a Unit or Quantity Kind does not have both a `qudt:symbol` and a `qudt:expression`. I just realized that I did not have this graph imported while working on the repo in Composer. Consequently, I did not catch that adding all those values for `qudt:symbol` in #577 causes a large number of validation errors from this constraint.

What's the appropriate fix for this? I might be missing it, but I can't seem to find any documentation explaining why a Unit or Quantity Kind shouldn't have both. Whatever the correct fix is, I'd be happy to implement it.

**Comment by steveraysteveray** [comment]
Since we have updated our use of qudt:symbol to be for Unicode representations, let me discuss this at our next Board call. We might relax this constraint...

**Comment by steveraysteveray** [comment]
We discussed this, and we agree that there's no reason anymore that we can't have both symbol and expression for an instance. I'll happily take you up on your offer to fix this if you could remove that SHACL constraint in a PR.
