### ISSUE TITLE
README inconsistent on OWL vs. SHACL default

### ISSUE THREAD

**Issue by Lenostatos** [qudt/qudt-public-repo#634]
In the README's [Installation/Configuration Instructions](https://github.com/qudt/qudt-public-repo#installation--configuration-instructions), it says that OWL is the default schema, while the opposite is indicated in the section above and in this guide: https://github.com/qudt/qudt-public-repo/wiki/Advanced-User-Guide#5-using-the-shacl-schema-instead-of-the-owl-schema

**Comment by steveraysteveray** [comment]
Thanks for catching that. We just switched from default OWL to default SHACL this month, and I missed that part of the documentation. Will fix it very soon!

**Comment by steveraysteveray** [comment]
Done.
