### ISSUE TITLE
USDollar-SameDay conforming to convention?

### ISSUE THREAD

**Issue by fkleedorfer** [qudt/qudt-public-repo#637]
I believe [`unit:USDollar-SameDay`](https://qudt.org/vocab/unit/USDollar-SameDay) does not conform to the convention, suggesting, its a combination of `unit:USDollar` and `unit:SameDay`. It should be renamed to `USDollar_SameDay`, if I am not mistaken. 

Correct? If so, I'll make a PR.

**Comment by steveraysteveray** [comment]
You are absolutely correct. Thanks.
