### ISSUE TITLE
Missing unit labels: mph, kph

### ISSUE THREAD

**Issue by aleppard** [qudt/qudt-public-repo#649]
Is there a philosophical reason not to include these common symbols for miles-per-hours and kilometres-per-hour?

**Comment by jhodgesatmb** [comment]
There are any number of units one would expect to be supported which might be missing. QUDT endeavors to support units from known international standards. We may not be up to date. Other units are submitted by interested individuals using a procedure you can find on the QUDT wiki.Jack Hodges, Ph.D.Arbor StudiosOn Feb 18, 2023, at 6:23 PM, Andrew Leppard ***@***.***> wrote:﻿
Is there a philosophical reason not to include these common symbols for miles-per-hours and kilometres-per-hour?

**Comment by steveraysteveray** [comment]
@aleppard, while what Jack says is true, we do have the units you mention: 
http://qudt.org/vocab/unit/KiloM-PER-HR
https://qudt.org/vocab/unit/MI-PER-HR

**Comment by steveraysteveray** [comment]
I just re-read the original question and realize you are only asking about the qudt:symbol. No reason why we couldn't include "mph" and "kph" as symbols for those units. Want to submit a pull request? :) 
(If you do, check if there is a Unicode equivalent first, as that is what we use whenever possible for symbols.)

**Comment by aleppard** [comment]
When I have a moment I'll see if I can submit a PR.

**Comment by fkleedorfer** [comment]
It was decided that there should be only one label per entity, see https://github.com/qudt/qudt-public-repo/discussions/895#discussioncomment-9076235. We need to find another way to express this if it is important.
