### ISSUE TITLE
Missing unit: CentiM-PER-YR

### ISSUE THREAD

**Issue by IfThen-Els** [qudt/qudt-public-repo#682]
We are missing the unit CentiM-PER-YR (cm/yr) in the quantitykind:Velocity. Could this be added?
cm/yr is used to indicate the indexation of water levels in polders in the Netherlands and it would be usefull if we could use the QUDT-unit.

**Comment by steveraysteveray** [comment]
Absolutely. Would you be interested/willing to submit a Pull Request? You can use our [guidelines](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines) to help. If not, it will go on the list and get added eventually. :)

**Comment by IfThen-Els** [comment]
Thanks, it's fine to have the request on the list while there is no urgency!
