### ISSUE TITLE
Incorrect dimension vector for unit:S-M2-PER-MOL

### ISSUE THREAD

**Issue by jsimonclark** [qudt/qudt-public-repo#690]
The term unit:S-M2-PER-MOL has dimension vector dimension:A0E2L-3I0M-1H0T3D0. However, it should be dimension:A-1E2L0I0M-1H0T3D0. 

unit:S has dimension:A0E2L-2I0M-1H0T3D0
unit:S-M2 has dimension:A0E2L0I0M-1H0T3D0
unit:S-M2-PER-MOL has dimension:A-1E2L0I0M-1H0T3D0

**Comment by steveraysteveray** [comment]
Thanks! Fixed in PR #692.
