### ISSUE TITLE
unit:UNITLESS qudt:symbol

### ISSUE THREAD

**Issue by kronmar** [qudt/qudt-public-repo#712]
Currently `unit:UNITLESS qudt:symbol "unitless"` which feels off. For reference `unit:NUM qudt:symbol "#"` which feels more in line with common uses one can find. 

My suggestions for improvement would either be `unit:UNITLESS qudt:symbol "1"` in line with the SI guidelines or `unit:UNITLESS qudt:symbol "-"` more in line with `unit:NUM`.

**Comment by steveraysteveray** [comment]
We discussed your suggestions, and we're agreeing that the best solution is to assign the symbol 一, which is Unicode  U+4E00. I'll go ahead and implement this myself, because I'm about to publish our latest release.
