### ISSUE TITLE
Symbol for unit:MilliGM-PER-DeciL

### ISSUE THREAD

**Issue by glow-mdsol** [qudt/qudt-public-repo#732]
Should the `qudt:symbol` for unit:MilliGM-PER-DeciL be 'mg/dL' rather than 'mg/L' as it currently is?  Ditto for the `qudt:expression "\\(mg/L\\)"^^qudt:LatexString`  - mg/dL is the recognised symbol used most often (for Blood Glucose as an example).  At the moment unit:MilliGM-PER-DeciL and unit:MilliGM-PER-L have the same symbol

**Comment by steveraysteveray** [comment]
Thanks for catching this!

**Comment by steveraysteveray** [comment]
Fixed in PR #736
