### ISSUE TITLE
Missing unit: MM-PER-M

### ISSUE THREAD

**Issue by IfThen-Els** [qudt/qudt-public-repo#738]
Hello! We are missing the unit millimeter per meter to express the slope of a roof or floor. Of course this can also be expressed with the angle in degrees but MM-PER-M is the common way... and we would like to use QUDT. Could this be added? (it hasn't got urgency)

**Comment by steveraysteveray** [comment]
Absolutely! It would have the URI unit:MilliM-PER-M. Would you like to try your hand at a Pull Request? See [instructions](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines).

**Comment by IfThen-Els** [comment]
I would like to do that but never done it before... (Only had a training for GitHub, no further experience). How do I make a new branch (first make a fork or...?)?

**Comment by steveraysteveray** [comment]
Yes, make a fork of this repo, and then follow the guidance from our wiki [here](https://github.com/qudt/qudt-public-repo/wiki/GoodGitPractices). As you make changes to the units file in your fork, please be aware of our [guidance for submitting new units](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines).

I'm sure you'll get the hang of it - it's a good learning experience!

**Comment by fkleedorfer** [comment]
MilliM-PER-M is now in QUDT
