### ISSUE TITLE
Clarification regarding Reflectance

### ISSUE THREAD

**Issue by mgberg** [qudt/qudt-public-repo#757]
https://github.com/qudt/qudt-public-repo/blob/41c8507eb9ab97b8b8db7aebc9495619229b1747/vocab/quantitykinds/VOCAB_QUDT-QUANTITY-KINDS-ALL-v2.1.ttl#L17545-L17571

The above link highlights two quantity kinds currently defined: 
1. `Reflectance`, which according to the description is explicitly for _sound power_.
2. `Refectance`, which according to the description is "fraction of incident electromagnetic power that is reflected at an interface".

The second URI and label (I think) is a typo, and the definition is consistent with reflectance as defined [here](https://en.wikipedia.org/wiki/Reflectance) which is the same page its `qudt:informativeReference` points to. 

Assuming that is a typo, presumably the typo should be fixed- but how should that be resolved given the existing `Reflectance`?

**Comment by steveraysteveray** [comment]
Wow! What a great catch! I think there are two options:
1. Mark Refectance as qudt:deprecated true, and broaden the definition and properties of Reflectance.
2. Just delete Refectance, but still broaden the definition and properties of Reflectance.

Let's see what others think.

**Comment by mgberg** [comment]
@steveraysteveray Another option would be to deprecate or delete `Refectance` and replace it with a duplicate of it with a new URI such as `ElectromagneticReflectance` if it is desired to keep them separate.

**Comment by mgberg** [comment]
@steveraysteveray Any additional insights on this?

**Comment by steveraysteveray** [comment]
Yes, see #764. We just merged both definitions into Reflectance since Refectance was a misspelling.
Pending review.

**Comment by mgberg** [comment]
Ah! I missed that, thanks!
