### ISSUE TITLE
Electron G Factor invalid value

### ISSUE THREAD

**Issue by mgberg** [qudt/qudt-public-repo#770]
This line contains an invalid value for `xsd:double` and therefore cannot be parsed by many tools.

https://github.com/qudt/qudt-public-repo/blob/13b466f33b152cc1c6d424ee2665628dc80b5eb3/vocab/constants/VOCAB_QUDT-CONSTANTS-v2.1.ttl#L3799C3-L3799C46

However, I'm hesitant to fix it because neither the value nor the standard uncertainty match that shown on the reference provided (https://physics.nist.gov/cgi-bin/cuu/Value?gem#mid)

**Comment by steveraysteveray** [comment]
Wow! I suggest we go with the NIST values. (Note to self: I should add a validation check for weird numbers like the one you found!)

Do you want to submit a PR?

**Comment by mgberg** [comment]
@steveraysteveray Sure, I can do that.
