### ISSUE TITLE
Cell Counts - best way to represent using QUDT

### ISSUE THREAD

**Issue by glow-mdsol** [qudt/qudt-public-repo#774]
In Hematology Panels, there are a number of Cell Counts; (eg White Blood Cells/Red Blood Cells in https://www.ncbi.nlm.nih.gov/books/NBK2263/table/ch1.T1/) - the units for these are usually some exponent for the 'absolute' count of cells per unit volume (eg 10^9/L or 10^3/mm^3); are the best units for these the NUM-PER-{VOL} or would it be worth adding a dedicated CELLS-PER-{VOL} with a dedicated Quantity kind?  Conversions in these cases are almost always orders of magnitude (where the count or volume scale up or down).   This would also include the UCUM /LPF and /HPF 'units'

**Comment by steveraysteveray** [comment]
I don't think creating a dedicated unit and quantity kind buys you anything. Ultimately the nature of CELLS-PER-\<some volume\> is the same as NUM-PER-\<some volume\>. They would both have a quantity kind of quantitykind:NumberDensity. The fact that you have exponential numbers is no problem. In fact, I'm currently re-testing our handling of 1.234E15 representations of numbers with the OWL schema (it's fine with SHACL). Pending my tests, I see no reason why the values of your quantities can not expressed with powers of 10.

**Comment by glow-mdsol** [comment]
Thanks!
