### ISSUE TITLE
qudt:isReplacedBy

### ISSUE THREAD

**Issue by mgberg** [qudt/qudt-public-repo#780]
I noticed that there are two usages of the property `qudt:isReplacedBy` in the entire repository (on `quantitykind:AmountOfSubstanceFractionOfB` and `quantitykind:AmountOfSubstanceConcentrationOfB`), but I don't see that property defined anywhere. Should that be a defined property or should it be `dcterms:isReplacedBy` instead?

**Comment by steveraysteveray** [comment]
Absolutely should be dcterms:isReplacedBy. That's on me - muscle memory just typed qudt:

As penance, I will do the PR for this!

**Comment by steveraysteveray** [comment]
Resolved in #781
