### ISSUE TITLE
websit missing links

### ISSUE THREAD

**Issue by vChavezB** [qudt/qudt-public-repo#791]
I was reading the website

https://www.qudt.org/pages/QUDToverviewPage.html

and the links for

http://www.linkedmodel.org/doc/2015/SCHEMA_vaem-v2.0

http://www.linkedmodel.org/doc/2015/SCHEMA_dtype-v1.2

are 404.

Im not sure this relates to the repository perse but wanted to notify the authors of this issue for the website.

**Comment by steveraysteveray** [comment]
Done.
