### ISSUE TITLE
Question: how to traverse the QUDT vocabularies

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#83]
Now that the QUDT vocabularies are online properly, they are starting to get some attention. 
So we can test to ensure that (a) the ontology is fit-for-purpose (b) the individuals are properly described. So I ran through this hypothetical, and got stuck:

convert a volume expressed in pints to litres. 

I find PINT - http://qudt.org/vocab/unit/PINT - where I'm told
```
unit:PINT a qudt:Unit ;
    qudt:conversionMultiplier 5.6826125E-4 ;
    qudt:conversionOffset 0.0 ;
    qudt:hasQuantityKind quantitykind:Volume ;
.
```
This gives the factor and offset to convert to the standard, reference units for 'volume' (everything else is annotations). But what is the standard unit for volume? 
So I look up http://qudt.org/vocab/quantitykind/Volume - where I'm told 
```
qk:Volume a qudt:QuantityKind ;
    qudt:baseUnitDimensions "L^3" , "m^3" ;    # this looks a little odd - m^3 isn't a dimension
    qudt:hasDimensionVector dimension:A0E0L3I0M0H0T0D0 ;
.
```
How do I find out what the reference units for this quantity kind is? Without that, I can't proceed. Where to now?

**Comment by steveraysteveray** [comment]
We haven't done as good a job as we should on documentation, but let me get straight to the answer. The reference units are always the SI units, so the conversion multiplier tells you what the unit in question equals in SI units.
Having said that, in fact the reference unit could be anything as long as you are just using it as the neutral unit enroute to your destination unit. Here's a query you might find useful in your environment, assuming you have QUDT loaded. Just change the string inside the query to anything you want (like "pint") and it will yield all other units possessing the same dimensionality.
I just ran it with "pint". The results are attached.
[pint.txt](https://github.com/qudt/qudt-public-repo/files/4428467/pint.txt)


PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX smf: <http://topbraid.org/sparqlmotionfunctions#>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
SELECT DISTINCT ?toConvert ?label ?into ?otherUnitLabel ?multiplyBy ?multiplier
WHERE {
  BIND ("To convert" AS ?toConvert) .
  BIND ("into" AS ?into) .
  BIND ("multiply by" AS ?multiplyBy) .
?unit a qudt:Unit .
?unit rdfs:label ?label .
FILTER (fn:contains (smf:lowerCase(?label), "tablespoon")) .
?unit qudt:conversionMultiplier ?cm1 .
?unit qudt:hasQuantityKind/qudt:hasDimensionVector ?qkdv .
?otherUnit qudt:hasQuantityKind/qudt:hasDimensionVector ?qkdv . 
?otherUnit a qudt:Unit .
FILTER (?otherUnit != ?unit) .
?otherUnit qudt:conversionMultiplier ?cm2 .
?otherUnit rdfs:label ?otherUnitLabel .
  BIND ((?cm1/?cm2) AS ?multiplier) .
}
ORDER BY ?label ?multiplier

**Comment by steveraysteveray** [comment]
Just noticed that, thanks to the query, I'm discovering that unit:PINT_US_DRY has the wrong conversion multiplier. I'll fix it soon.

**Comment by steveraysteveray** [comment]
Fixed in PR #84

**Comment by dr-shorthair** [comment]
> The reference units are always the SI units

Yeah - I kind of understood that. But shouldn't it be made explicit? Else can it be inferred directly from the the dimensionality.

**Comment by dr-shorthair** [comment]
Also - what about my # comment here
```
qk:Volume a qudt:QuantityKind ;
    qudt:baseUnitDimensions "L^3" , "m^3" ;    # this looks a little odd - m^3 isn't a dimension
    qudt:hasDimensionVector dimension:A0E0L3I0M0H0T0D0 ;
.
```
`m^3` doesn't look like a 'dimension' to me. It looks like a base-unit, except I would have expected to see the URI `unit:M3`.

**Comment by steveraysteveray** [comment]
Good points, all. 
We need to clean some (many?) of these up. Your example (in a different post of quantitykind:Area is a better model of how to handle it.
In some cases, we might not have the base unit combination defined as an explicit unit, but in this case we do. Still trying to decide which would be better, m^3 or unit:M3. I can see some good arguments for either one.

**Comment by steveraysteveray** [comment]
> > The reference units are always the SI units
> 
> Yeah - I kind of understood that. But shouldn't it be made explicit? Else can it be inferred directly from the dimensionality.

I plan to start working on a user guide soon, probably in the wiki, but I'm guessing you think it should also be explicitly in the model?

**Comment by dr-shorthair** [comment]
> Still trying to decide which would be better, m^3 or unit:M3. 

`m^3` is a symbol. `unit:M3` is an identifier. The latter takes you right to the definition. The symbol only gets you there via a query. 

I understand your point that when doing a two-step conversion it doesn't actually matter. But if you want the quantity expressed in the 'canonical' units, you would just use the `conversionMultiplier` and `conversionOffset` but then don't know what the units are! As it stands there is not even a path through the graph to get to the base unit - or if there is it is a very long one. 

My feeling is that the important relationships should always be explicit.
