### ISSUE TITLE
Importing qudt in another ontology in Protege

### ISSUE THREAD

**Issue by vChavezB** [qudt/qudt-public-repo#842]
I am a qudt user that is developing an ontology with Protégé. After some testing I found a bug in the owlapi related to resolving the IRI of the ontology (See https://github.com/owlcs/owlapi/issues/1080). In particular this happens because qudt has an annotation value that points to the IRI of the ontology

https://github.com/qudt/qudt-public-repo/blob/22e44ae9be6694a5e547179027b67d0d645cb261/schema/SCHEMA_QUDT-v2.1.ttl#L78

This bug does not allow to properly use qudt in protege if its imported in another ontology. The main problem is that protege does not load qudt correctly and autocomplete functionality, inference and ontologies that want to import qudt will not work.

Below you will find how to reproduce this issue. I know this is not fault of QUDT but of the owlapi (used by Protege). Hence I would like to document this issue so other Protege users are aware of this when using QUDT. You will note that I also include screenshots of how this should look like. This is because I [fixed this ](https://github.com/owlcs/owlapi/pull/1117):) but it is still not merged in to owlapi nor Protege (which will probably take a long time).

## Example

Open this turtle ontology in Protege

```turtle
@prefix : <www.usecase1.com/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <www.usecase1.com/> .

<urn:absolute:www.usecase1.com> rdf:type owl:Ontology ;
                                owl:imports <http://qudt.org/schema/qudt> .
:MyClass rdf:type owl:Class .

:MySubclass rdf:type owl:Class ;
            rdfs:subClassOf :MyClass .
```

### Expected behavior

QUDT Classes are loaded and import is shown correctly:

<img src="https://github.com/qudt/qudt-public-repo/assets/47216966/5dc1ba29-9348-4ff8-9175-2665dcb49571" alt=""  width="200" height="350" />

<img src="https://github.com/qudt/qudt-public-repo/assets/47216966/b005c1f7-77b1-49d5-80d8-bf214af475a0" alt=""  width="350" height="200" />

### Actual behavior

Not all classes are loaded and the import information is not complete.

<img src="https://github.com/qudt/qudt-public-repo/assets/47216966/b9deb81e-ffc6-49d0-baf2-c14475a373b4" alt=""  width="200" height="200" />
<img src="https://github.com/qudt/qudt-public-repo/assets/47216966/73806885-59b4-4467-ad96-efbe9778c2f7" alt=""  width="350" height="150" />

**Comment by steveraysteveray** [comment]
@vChavezB, thanks for your comments. I have a question and an observation:

Question: Have you tried your example, but importing <http://qudt.org/2.1/schema/qudt>, i.e. the versioned schema? I'm wondering if that might work better.

Observation: You are probably aware that importing just the schema without the vocabularies will not give you the benefit of all the unit etc. definitions. Try importing <http://qudt.org/2.1/vocab/unit> and let me know how that goes.

**Comment by vChavezB** [comment]
# Tests with namespace http://qudt.org/2.1/

> Have you tried your example, but importing http://qudt.org/2.1/schema/qudt, i.e. the versioned schema? I'm wondering if that might work better.

@steveraysteveray  The same behaviour occured as the one I posted above where not all qudt classes are loaded correctly.


> Try importing http://qudt.org/2.1/vocab/unit and let me know how that goes.

It loads the unit vocabulary but when loaded in protege it shows assertions of individuals as annotation properties. Which I think happens because http://qudt.org/2.1/schema/qudt was not loaded correctly.

![grafik](https://github.com/qudt/qudt-public-repo/assets/47216966/d0fa3698-8d39-422e-8d97-f24d5e746443)

This is how the same individual looks with the patch I made for the owlapi in Protege

![grafik](https://github.com/qudt/qudt-public-repo/assets/47216966/907be10a-ca9b-4e51-a5bf-60efaccbf703)



## Final thoughts

> You are probably aware that importing just the schema without the vocabularies will not give you the benefit of all the unit etc. definitions.

Oh yes I am aware of this. Part of my research project involves developing software that loads an ontology that imports qudt. Thats the reason I went down the rabbit hole to make qudt work with the owlapi (and protege) which so far works fine with SWRL queries and reasoning engines. The only thing I have noticed is that it takes around 70 seconds when an ontology imports the vocabularies: unit, quantityKind, dimensionVector with Protege and externally in Java directly with the owlapi.

**Comment by steveraysteveray** [comment]
I just tried duplicating your screen shots above, and found that using Protege 5.5.0 it works correctly. I had earlier had problems with the more recent versions of Protege, which is why we had included the disclaimer in the Readme:

_Disclaimer: The QUDT ontologies have been tested to load without error only in Protege 5.5.0, but not later releases._

Perhaps you could test 5.5.0 as well to see if you get the same behavior as I do? If so, could you refine the documentation in your PR to reflect that?

**Comment by steveraysteveray** [comment]
Actually, let me add that I only tested by directly uploading http://qudt.org/2.1/vocab/unit, not importing it. Is that consistent with your findings?

**Comment by vChavezB** [comment]
Hello @steveraysteveray. Yes, forgot to mention the results I posted in https://github.com/qudt/qudt-public-repo/issues/842#issuecomment-1877915155 were with the ontology that imports qudt. As github has blacklisted ttl files I will post the modified turtle file here as text

```turtle
@prefix : <www.usecase1.com/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <www.usecase1.com/> .

<urn:absolute:www.usecase1.com> rdf:type owl:Ontology ;
                                owl:imports <http://qudt.org/2.1/vocab/unit> .
:MyClass rdf:type owl:Class .

:MySubclass rdf:type owl:Class ;
            rdfs:subClassOf :MyClass .
```

**Comment by steveraysteveray** [comment]
I just tried using your turtle file, and it seems to work correctly with Protege 5.5.0.

It does still mess up in showing the graph IRIs:

![image](https://github.com/qudt/qudt-public-repo/assets/1130189/251de9c2-ad0e-4756-872a-8733a4a9e509)

...but otherwise seems OK.

**Comment by vChavezB** [comment]
Is that screenshot with the turtle file from my previous [comment](https://github.com/qudt/qudt-public-repo/issues/842#issuecomment-1878773419)? In that comment I import http://qudt.org/2.1/vocab/unit

![grafik](https://github.com/qudt/qudt-public-repo/assets/47216966/423b578d-d2a1-4580-8453-575bad53cb1c)

**Comment by steveraysteveray** [comment]
Yes, it is.

**Comment by steveraysteveray** [comment]
I only captured part of the "Imported ontologies" pane. It would take some more digging to figure out why some graphs are listed correctly and some not. Here's a bit more:

![image](https://github.com/qudt/qudt-public-repo/assets/1130189/19bbbcb3-9aa9-42b9-acf5-bea90acc76b0)

**Comment by vChavezB** [comment]
The reason some imported ontologies are listed with the incorrect IRI has to do with the owlapi bug I mentioned

I think I have noticed that the difference I got was because I have been loading directly http://qudt.org/vocab/unit instead of the versioned iri (http://qudt.org/2.1/vocab/unit).

Now I get the same result as you with Protege 5.5.0.

I will change my ontology imports to the namespace http://qudt.org/2.1 and try to see if the software I am working on still behaves the same or if I need the owlapi patch to solve the IRI bug.

To be continued...

**Comment by steveraysteveray** [comment]
Many thanks! We can update the Readme PR accordingly, based on what you find.

**Comment by vChavezB** [comment]
## Works with Protege is using qudt.org/2.1

I have tested it further and it seems to work correctly in Protege if the versioned IRI is used (http://qudt.org/2.1).

## Use with other ontology APIs

However for the case where I am working in java with the owlapi and loading the ontology that imports qudt I get an error due to the bug with the IRI. 

So I am not sure how important for the qudt organization it is to document this. I can change this in the PR but this is a really specific use case where I am using qudt to develop a software and might be of interest only for software developers that want to use qudt. So far my experience has been:

1. [owlapi](https://owlcs.github.io/owlapi/) (java): Has a bug with IRI name resolution and does not allow to load qudt.
2. [owlready2](https://owlready2.readthedocs.io/en/latest/) (python):  Does not load turtle files, only accepts rdf
3. [Apache Jena](https://jena.apache.org/) (java): Loads correctly. 
4. [owlcs/ont-api](https://github.com/owlcs/ont-api) (java): Loads correctly.

**Comment by steveraysteveray** [comment]
How about you include a link to the above comment (https://github.com/qudt/qudt-public-repo/issues/842#issuecomment-1879114604) in an edit to your PR and we leave it at that? Something like: "Please note that various libraries exhibit different behaviors when importing the QUDT ontology, see ..."

**Comment by vChavezB** [comment]
Ok seems good to me. I will close this issue as it was solved by importing qudt with versioned IRI.
