### ISSUE TITLE
Missing unit:  Gauge Pressure | Or is it just a Relative Pressure to Ambient Pressure?

### ISSUE THREAD

**Issue by TKaluza** [qudt/qudt-public-repo#849]
Hello QUDT world!

I've been exploring the QUDT ontology and appreciate the extensive work put into this valuable resource. While navigating the ontology, I noticed that the term 'Gauge Pressure' does not seem to be explicitly listed. **Gauge Pressure** - as fas as I know is commonly understood as pressure relative to **atmospheric pressure**. This a fundamental concept in engineering applications. Also I understand that Gauge Pressure can be always viewed as a type of **relative pressure** to **ambient pressue**. 

1. 'Gauge Pressure' is indeed included in the ontology under a different term or as a subset of relative pressure?
2. If it's not currently included, would you consider its addition to the ontology as a distinct entry? If yes I can make a PR Request 👍 

Thank you for your attention to this matter and for your ongoing efforts in maintaining and improving the QUDT ontology.

**Comment by steveraysteveray** [comment]
Your suggestion sounds reasonable. Please let us know if you have any issues with the PR.

Thanks!

**Comment by steveraysteveray** [comment]
Issue resolved by #948.
