### ISSUE TITLE
The unit Turtle file not found at qudt.org

### ISSUE THREAD

**Issue by jbkoh** [qudt/qudt-public-repo#860]
Hi @steveraysteveray,

I just found that "https://qudt.org/2.1/vocab/unit" is not accessible anymore with 404 error. Is this something you are aware of?

**Comment by jbkoh** [comment]
closing this as it's working now.

**Comment by steveraysteveray** [comment]
Sorry about that! I was trying out a setting in httpd.conf in pursuit of a CORS error. We now believe the error was on the client's end, not the server.

**Comment by jbkoh** [comment]
I think I was in that short window haha. It's all good now. Thanks for the response!
