### ISSUE TITLE
Alignment with SI Digital Framework

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#862]
BIPM has (finally) developed a digital framework for the SI, with persistent URIs for 
- [Units](https://si-digital-framework.org/SI/units) 
  - with the pattern https://si-digital-framework.org/SI/units/ampere etc
- [Quantities](https://si-digital-framework.org/quantities) (i.e. QuantityKinds) 
  - with the pattern https://si-digital-framework.org/quantities/ELCU etc
- [Prefixes](https://si-digital-framework.org/SI/prefixes) 
  - with the pattern https://si-digital-framework.org/SI/prefixes/micro etc
- [Defining Constants](https://si-digital-framework.org/constants) 
  - with the pattern https://si-digital-framework.org/constants/PlanckConstant etc
- [Decisions](https://si-digital-framework.org/SI/decisions) 
  - mostly DOIs e.g. https://doi.org/10.59161/cgpm2018res1e  

(Its a shame they used plurals in the URIs, but whatever ...) 

The web UI is https://si-digital-framework.org/ 
The underlying representation is RDF, the sources are at https://github.com/TheBIPM/SI_Digital_Framework/tree/main/SI_Reference_Point/TTL 

I haven't yet found out how to get RDF representations from the service - HTTP content negotiation can get JSON or XML but not RDF/XML, JSON-LD or Turtle - so I'm chasing this up with my contact at BIPM. 

Nevertheless, there is an opportunity to tie QUDT definitions back to the SI reference point. 

The number of individuals in the SI system are still relatively small - there are only ca. 100 units, and smaller numbers of the other things - so a manual matching process is tractable. 

**What matching predicate should be used?** 

- `skos:exactMatch` would entail the SI individuals are (also) `rdf:type skos:Concept` which is probably harmless 
- however, this may be one of those rare cases where `owl:sameAs` is actually appropriate. 

The [SI 'ontology'](https://github.com/TheBIPM/SI_Digital_Framework/blob/main/SI_Reference_Point/TTL/si.ttl) looks a bit simpler than QUDT so I don't expect there would be inconsistencies with `sameAs`, but that probably needs to be verified.

**Comment by steveraysteveray** [comment]
Very interesting. We will have to investigate the pros & cons, especially concerning owl:sameAs that, as you know, carries baggage.

**Comment by stuchalk** [comment]
I was involved in the development of the site, so let me know if I can help.  Simon, I pitched for singular for the individual units, prefixes, etc. but they decided not to go with it...sigh.

**Comment by steveraysteveray** [comment]
@stuchalk, as you probably have seen in #865, we have been discussing the best name for the relation to point to the SI URIs. A question for you is what is the timetable for when or if the SI infrastructure will offer resolution of the URIs to computable objects in addition to html pages? (Much like the way http://qudt.org/vocab/unit/A resolves to an html page for browsers, but to a .ttl object for programs). The timetable will influence whether we will offer just an informational reference, or a computable link.

**Comment by steveraysteveray** [comment]
That's good news. How do we access the units endpoint to get the JSON-LD?

**Comment by steveraysteveray** [comment]
No worries. I figured it out using Postman.

**Comment by steveraysteveray** [comment]
@stuchalk, I'm curious why your URIs sometimes contain a /SI (units) and sometimes do not (constants)?

**Comment by stuchalk** [comment]
@steveraysteveray that's because the units and prefixes are part of the SI, but the constants fall under the CODATA TG on the fundamental constants.  Still, I also wish these were harmonized on there format.

**Comment by steveraysteveray** [comment]
At least there's an explanation!
