### ISSUE TITLE
Unit for net tonnage

### ISSUE THREAD

**Issue by veleda** [qudt/qudt-public-repo#894]
A while ago, I posted a request for the definition of gross tonnage (#158). Is it possible to get the definition of [net tonnage](https://en.wikipedia.org/wiki/Net_tonnage) in QUDT Unit too? 

#### Suggestion
`qudt:conversionMultiplier`, `qudt:conversionMultiplierSN` and `qudt:hasDimensionVector` copied from `unit:GT`.
```
unit:NT
  rdf:type qudt:Unit ;
  rdfs:label "Net tonnage"@en ;
  qudt:conversionMultiplier 0.0 ;
  qudt:conversionMultiplierSN 0.0E0 ;
  qudt:hasDimensionVector qkdv:A0E0L3I0M0H0T0D0 ;
  qudt:plainTextDescription "Net tonnage is not a measure of the weight of the ship or its cargo, and should not be confused with terms such as deadweight tonnage or displacement. Also, unlike the net register tonnage, the net tonnage is unitless and thus can not be defined as "tons" or "net tons"." ;
  qudt:hasQuantityKind quantitykind:Volume ; 
  qudt:symbol "N.T." ;
  rdfs:seeAlso unit:RT
  rdfs:isDefinedBy <http://qudt.org/vocab/unit> ;
.
```

**Comment by fkleedorfer** [comment]
If it's unitless, should it not be a `qudt:QuantityKind`?

**Comment by steveraysteveray** [comment]
We discussed this for unit:GT, Gross Tonnage, and concluded it was a nonlinear unit related to volume. This is much the same. I adjusted the description to not say it was unitless.

**Comment by steveraysteveray** [comment]
Done in PR #896.
