### ISSUE TITLE
Incorrect or duplicate meta data for unit A-SEC2

### ISSUE THREAD

**Issue by berrisfordjohn** [qudt/qudt-public-repo#911]
In https://github.com/qudt/qudt-public-repo/blob/main/vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
there are two units which appear to be accidental duplicates of each other

unit:A-SEC2
  a qudt:Unit ;
  dcterms:description "product out of the power of the SI base unit ampere with the exponent 2 and the SI base unit second" ;
  qudt:conversionMultiplier 1.0 ;
  qudt:conversionMultiplierSN 1.0E0 ;
  qudt:hasDimensionVector qkdv:A0E1L0I0M0H0T2D0 ;
  qudt:hasQuantityKind quantitykind:Unknown ;
  qudt:iec61360Code "0112/2///62720#UAA108" ;
  qudt:symbol "A²·s" ;
  qudt:ucumCode "A.s2"^^qudt:UCUMcs ;
  qudt:uneceCommonCode "H32" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "ampere squared second" ;
.
unit:A2-SEC
  a qudt:Unit ;
  dcterms:description "product out of the power of the SI base unit ampere with the exponent 2 and the SI base unit second" ;
  qudt:conversionMultiplier 1.0 ;
  qudt:conversionMultiplierSN 1.0E0 ;
  qudt:hasDimensionVector qkdv:A0E2L0I0M0H0T1D0 ;
  qudt:hasQuantityKind quantitykind:Unknown ;
  qudt:iec61360Code "0112/2///62720#UAA108" ;
  qudt:symbol "A²·s" ;
  qudt:ucumCode "A2.s"^^qudt:UCUMcs ;
  qudt:uneceCommonCode "H32" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "ampere squared second" ;

The first one, A-SEC2, appears to have incorrect dcterms:description; qudt:symbol; qudt:iec61360Code;  qudt:uneceCommonCode and rdfs:label
with the incorrect values appearing to have come from A2-SEC.

Regards

**Comment by steveraysteveray** [comment]
Ah yes. This seems to have slipped in during our harmonization activity of many units from IEC 61360, but you are absolutely correct. Would you be willing to dig into the correct codes for each of these? I believe A2-SEC has UNECE code H31 rather than H32, but I have not confirmed that. All we need are the codes for iec61360, UCUM an UNECE (and to fix the qudt:symbol and description).

Let me know if you don't want to jump into this.

**Comment by berrisfordjohn** [comment]
pull request https://github.com/qudt/qudt-public-repo/pull/919
