### ISSUE TITLE
update rdfs:label for M3-PER-MOL-SEC

### ISSUE THREAD

**Issue by berrisfordjohn** [qudt/qudt-public-repo#912]
The rdfs:label for M3-PER-MOL-SEC references centimeters instead of meters

Suggested change from
rdfs:label "Cubic Centimeter per Mole Second"@en ;
rdfs:label "Cubic Centimeter per Mole Second"@en-us ;

to 
rdfs:label "Cubic Metre per Mole Second"@en ;
rdfs:label "Cubic Meter per Mole Second"@en-us ;

i.e.
![image](https://github.com/qudt/qudt-public-repo/assets/12910519/95d95355-ecb4-4776-b5ee-252d7ef645ed)

I did try to create a pull request but I don't seem have to write access to create a branch (understandable).

**Comment by steveraysteveray** [comment]
I appreciate your deep digging into QUDT! I'm afraid some of the more "cosmetic" parts (like the labels) do indeed need more scrutiny, so this is great. As far as write access, we are urging contributors to use a fork for changes (described [here](https://github.com/qudt/qudt-public-repo/wiki/GoodGitPractices))

**Comment by berrisfordjohn** [comment]
Hi
No problem at all.
I'm happy to raise pull requests for these issues - for some reason i wasn't able to make a branch in the repo (I suspect the issue is at my end). If i can work this out I'll raise pull requests.

As to how I'm spotting these issues - I've extracted the data from qudt and then systematically looking for duplicate labels for different qudt units

**Comment by steveraysteveray** [comment]
You got my curiousity going, and I have found 27 distinct units that share the same IEC 61360 code and are not intentionally dual entries (i.e. either via deprecation, or where they share qudt:exactMatch).

**Comment by fkleedorfer** [comment]
> I'm happy to raise pull requests for these issues - for some reason i wasn't able to make a branch in the repo (I suspect the issue is at my end). If i can work this out I'll raise pull requests.

You need to fork the repository, then commit changes to your fork, then you can make a PR.

**Comment by berrisfordjohn** [comment]
related pull request https://github.com/qudt/qudt-public-repo/pull/914
