### ISSUE TITLE
GigaBIT-PER-M seems to be a copy of GibiBIT-PER-M

### ISSUE THREAD

**Issue by berrisfordjohn** [qudt/qudt-public-repo#913]
The attributes for GigaBIT-PER-M seem to be a copy of GibiBIT-PER-M but should be distinct

current GigaBIT-PER-M

unit:GigaBIT-PER-M
  a qudt:Unit ;
  dcterms:description "1,073,741,824-fold of the unit bit divided by the SI base unit metre" ;
  qudt:conversionMultiplier 693147180.55994530941723212145818 ;
  qudt:conversionMultiplierSN 6.9314718055994530941723212145818E8 ;
  qudt:hasDimensionVector qkdv:A0E0L-1I0M0H0T0D0 ;
  qudt:hasQuantityKind quantitykind:LinearBitDensity ;
  qudt:iec61360Code "0112/2///62720#UAA159" ;
  qudt:symbol "Gibit/m" ;
  qudt:ucumCode "Gbit.m-1"^^qudt:UCUMcs ;
  qudt:uneceCommonCode "E69" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "gibibit per metre" ;

current GibiBIT-PER-M

unit:GibiBIT-PER-M
  a qudt:Unit ;
  dcterms:description "1,073,741,824-fold of the unit bit divided by the SI base unit metre" ;
  qudt:conversionMultiplier 744261117.95489301787390319512589573292032 ;
  qudt:conversionMultiplierSN 7.4426111795489301787390319512589573292032E8 ;
  qudt:hasDimensionVector qkdv:A0E0L-1I0M0H0T0D0 ;
  qudt:hasQuantityKind quantitykind:LinearBitDensity ;
  qudt:iec61360Code "0112/2///62720#UAA159" ;
  qudt:symbol "Gibit/m" ;
  qudt:ucumCode "Gibit.m-1"^^qudt:UCUMcs ;
  qudt:uneceCommonCode "E69" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "gibibit per metre" ;

note the two are identical but should be distinct

for example the description and rdfs:label should be
unit:GigaBIT-PER-M
  a qudt:Unit ;
  dcterms:description "1,000,000,000-fold of the unit bit divided by the SI base unit metre" ;
  rdfs:label "gigabit per metre" ;

other attributes appear to be incorrect but I'm unsure how to correct:
qudt:symbol "Gibit/m" ;
qudt:ucumCode "Gibit.m-1"^^qudt:UCUMcs ;

Regards
John

**Comment by steveraysteveray** [comment]
Yes. The same harmonization event. 

Eagerly awaiting your response on whether you plan to tackle some/all of these errors. Also, I'm curious whether you are using some automated tool to uncover them?

**Comment by berrisfordjohn** [comment]
pull request https://github.com/qudt/qudt-public-repo/pull/916

**Comment by berrisfordjohn** [comment]
resolved
