### ISSUE TITLE
unit:KiloCAL and unit:KiloCAL_TH are the same unit but have different ucum, unece and iec61360 codes

### ISSUE THREAD

**Issue by berrisfordjohn** [qudt/qudt-public-repo#928]
It appears that unit:KiloCAL and unit:KiloCAL_TH are the same unit - based on conversion multipliers and dimension vector and qudt:symbol
However, ucum, unece and iec61360 are different in the two units. 

Raised as an issue, rather than a pull request, as I'm unsure of the exact resolution for this issue. It may be that the current two units are correct.

UCUM have an interesting discussion on disambiguating the various types of calorie
https://ucum.org/ucum#section-Other-Legacy-Units

**Comment by steveraysteveray** [comment]
Fixed in #941
