### ISSUE TITLE
Rate of Change

### ISSUE THREAD

**Issue by gwemon** [qudt/qudt-public-repo#933]
Hi, I noticed while checking for quantity kinds in QUDT, that there seems to be a duplicate entry for "Rate of Change of Temperature" (http://qudt.org/vocab/quantitykind/RateOfChangeOfTemperature) and "Temperature Rate of Change" (http://qudt.org/vocab/quantitykind/TemperatureRateOfChange). Many thanks, Gwen.

**Comment by steveraysteveray** [comment]
Thanks for spotting this. http://qudt.org/vocab/quantitykind/RateOfChangeOfTemperature was a recent addition, which will be merged with http://qudt.org/vocab/quantitykind/TemperatureRateOfChange.
