### ISSUE TITLE
quantitykind:ReactivePower: typos in description

### ISSUE THREAD

**Issue by VladimirAlexiev** [qudt/qudt-public-repo#940]
https://qudt.org/vocab/quantitykind/
`dcterms:description "\"Reactive Power}, ..."^^qudt:LatexString ;`: the `}` is a typo,
should be `"\"Reactive Power\", ...`

BTW, https://github.com/search?q=repo%3Aqudt%2Fqudt-public-repo%20reactivepower&type=code doesn't find this file?

**Comment by fkleedorfer** [comment]
Thanks! If you want, please feel free to fork the repository, making the change and creating a pull request!

**Comment by steveraysteveray** [comment]
Regarding your BTW comment, I looked into that and found the following GitHub documentation:
```
Beyond that, we also don't include all files in the search index:
...
Empty files and files over 350 kiB are excluded
```

The quantity kind vocabulary file is 1.6MB. That file, and the units vocabulary file (2.1MB) will thus never get searched this way.

**Comment by steveraysteveray** [comment]
Resolved.
