### ISSUE TITLE
inconsistent `derivedCoherentUnitOfSystem, hasBaseUnit` and `conversionMultiplier`

### ISSUE THREAD

**Issue by VladimirAlexiev** [qudt/qudt-public-repo#952]
- `qudt:derivedCoherentUnitOfSystem` is defined as "unit system in which the unit is derived from the system's base units with a proportionality constant of one",
- So I thought these are exactly the units with `qudt:conversionMultiplier 1.0`.
- But then I also thought that the base units of a system would also have multiplier 1.
- So let's call these "fundamental" units, which we can find with a property path like this: 
`?unit qudt:derivedCoherentUnitOfSystem|^qudt:hasBaseUnit ?sys`

Despite #951, let's try to check with SPARQL at https://www.qudt.org/fuseki/#/dataset/qudt/query
- there are 143 fundamental (127 coherent) units:
```sparql
SELECT distinct ?unit WHERE {
 ?unit qudt:derivedCoherentUnitOfSystem|^qudt:hasBaseUnit ?sys
}
```
- 27 (19) of them don't have multiplier 1.0. 
Eg is `MilliM3-PER-KiloGM` really coherent? I thought only `M3-PER-KiloGM` is
```sparql
SELECT distinct ?unit WHERE {
  ?unit qudt:derivedCoherentUnitOfSystem|^qudt:hasBaseUnit ?sys
  filter not exists {?unit qudt:conversionMultiplier 1.0}
} 
```
- 302 units have multiplier 1, but are not fundamental for any system:
Eg shoudn't `henry per meter`, the unit of magnetic permeability, be declared to be "coherent", although it can be reduced to the base units `kilogram meter per square second per square ampere`?
Eg why `J, W, OHM` and even `M2` are not declared "coherent"?
```sparql
SELECT distinct ?unit WHERE {
  ?unit qudt:conversionMultiplier 1.0
  filter not exists {?unit qudt:derivedCoherentUnitOfSystem|^qudt:hasBaseUnit ?sys}
} 
```

**Comment by steveraysteveray** [comment]
@VladimirAlexiev, you are correct in pointing out that we have not paid much attention to maintaining the completeness or correctness of the family of properties:
<img width="292" alt="image" src="https://github.com/user-attachments/assets/c563f76f-ad05-44ab-84bc-1a107aaa7a82">
Perhaps we can work together on composing some queries to put things back into good order, plus create some validation rules for checking the vocabulary going forward. I will get started on this.
