### ISSUE TITLE
Use of qudt:hasDimensionVector in datatypes file clashes with other uses

### ISSUE THREAD

**Issue by fkleedorfer** [qudt/qudt-public-repo#992]
The `qudt:hasDimensionVector` here is wrong, I believe:
```
qudt:MATRIX-4X4-FLOATDP
  a qudt:Matrix ;
  qudt:code 320 ;
  qudt:dimensionality 2 ;
  qudt:elementType qudt:FLOAT-DP ;
  qudt:hasDimensionVector [
      a qudt:DimensionVector ;
      rdf:first "4"^^xsd:int ;
      rdf:rest (
          "4"^^xsd:int
        ) ;
      rdfs:label "4 by 4 array" ;
    ] ;
  qudt:typeMatrix <http://qudt.org/schema/type#TYPE-MATRIX-4x4-FLOATDP> ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/datatype> ;
 [...]
```
I don't really know what this definition is used for (if anything), but it trips up the turtle-formatter. 
It seems that it is an accident to call it 'dimensionVector' - which, in its widely used meaning denotes the SI dimension vector. Here, it seems to denote the dimensions of a matrix

How about we change it to

```
qudt:dimensions (4 4);
```

**Comment by fkleedorfer** [comment]
in this file, we also use `qudt:dimension` for objects which have `qudt:dimensionality 1`, which indicates that `qudt:dimensions` would be an appropriate name for the property.

one could even go so far as to replace all uses of `qudt:dimension N` with `qudt:dimensions ( N )`.

**Comment by steveraysteveray** [comment]
I'm not aware of any uses of our matrix definitions, but I'm fine with this. I turn to @ralphtq and @jhodgesatmb who might know more about this.

**Comment by ralphtq** [comment]
resolved
